import { useState, useEffect, useCallback } from 'react';
import toast from 'react-hot-toast';
import { useI18n } from '@/i18n/provider';
import { organizationService, type CompanyGroup } from '@/services/organization.service';
import { PageHeader } from '@/components/shared/PageHeader';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Plus, Search, RefreshCw, Building2, Pencil, Trash2 } from 'lucide-react';
import { formatDate } from '@/utils/format';
import { apiErrorMessage } from '@/lib/errors';

// ─── Modal ──────────────────────────────────────────────
function Modal({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: React.ReactNode }) {
  if (!open) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40" onClick={onClose}>
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-xl border border-border w-full max-w-lg mx-4" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between px-5 py-4 border-b border-border">
          <h2 className="text-base font-semibold">{title}</h2>
          <button onClick={onClose} className="text-muted-foreground hover:text-foreground p-1">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M18 6L6 18M6 6l12 12"/></svg>
          </button>
        </div>
        <div className="p-5">{children}</div>
      </div>
    </div>
  );
}

function ConfirmDialog({ open, onClose, onConfirm, title, message }: {
  open: boolean; onClose: () => void; onConfirm: () => void;
  title: string; message: string;
}) {
  const { t } = useI18n();
  if (!open) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40" onClick={onClose}>
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-xl border border-border w-full max-w-sm mx-4" onClick={(e) => e.stopPropagation()}>
        <div className="p-5">
          <h3 className="text-base font-semibold mb-2">{title}</h3>
          <p className="text-sm text-muted-foreground">{message}</p>
        </div>
        <div className="flex justify-end gap-2 px-5 py-3 border-t border-border">
          <Button variant="outline" size="sm" onClick={onClose}>{t('common.cancel')}</Button>
          <Button size="sm" onClick={onConfirm} className="bg-red-600 hover:bg-red-700">{t('common.delete')}</Button>
        </div>
      </div>
    </div>
  );
}

function GroupForm({ initial, onSave, onClose }: {
  initial?: Partial<CompanyGroup>;
  onSave: (data: Partial<CompanyGroup>) => Promise<void>;
  onClose: () => void;
}) {
  const { t } = useI18n();
  const [name, setName] = useState(initial?.name || '');
  const [saving, setSaving] = useState(false);
  const isEdit = Boolean(initial?.id);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return toast.error(t('wf.common.nameRequired'));
    setSaving(true);
    try {
      await onSave({ name: name.trim() });
      onClose();
    } catch { /* handled */ }
    finally { setSaving(false); }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="block text-xs font-medium text-muted-foreground mb-1.5">{t('wf.org.groups.form.name')} *</label>
          <Input value={name} onChange={(e) => setName(e.target.value)} placeholder={t('wf.org.groups.form.namePlaceholder')} required />
        </div>
        <div>
          <label className="block text-xs font-medium text-muted-foreground mb-1.5">{t('wf.common.code')}</label>
          <Input value={isEdit ? initial?.code || '' : ''} disabled placeholder={t('wf.common.autoGenerated')} />
        </div>
      </div>
      <div className="flex justify-end gap-2 pt-2">
        <Button type="button" variant="outline" size="sm" onClick={onClose}>{t('common.cancel')}</Button>
        <Button type="submit" size="sm" disabled={saving}>{saving ? t('wf.common.saving') : t('common.save')}</Button>
      </div>
    </form>
  );
}

export function GroupListPage() {
  const { t } = useI18n();
  const [groups, setGroups] = useState<CompanyGroup[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [showCreate, setShowCreate] = useState(false);
  const [editing, setEditing] = useState<CompanyGroup | null>(null);
  const [deleting, setDeleting] = useState<CompanyGroup | null>(null);

  const fetchGroups = useCallback(async () => {
    setLoading(true);
    try {
      const data = await organizationService.getGroups();
      setGroups(data);
    } catch (error) {
      console.error('Failed to fetch groups:', error);
      toast.error(t('wf.org.groups.toast.loadFailed'));
    } finally {
      setLoading(false);
    }
  }, [t]);

  useEffect(() => { fetchGroups(); }, [fetchGroups]);

  const handleCreate = async (data: Partial<CompanyGroup>) => {
    try {
      await organizationService.createGroup(data);
      toast.success(t('wf.org.groups.toast.created'));
      setShowCreate(false);
      fetchGroups();
    } catch (err) {
      toast.error(apiErrorMessage(err, t('wf.org.groups.toast.createFailed')));
      throw err;
    }
  };

  const handleUpdate = async (data: Partial<CompanyGroup>) => {
    if (!editing) return;
    try {
      await organizationService.updateGroup(editing.id, data);
      toast.success(t('wf.org.groups.toast.updated'));
      setEditing(null);
      fetchGroups();
    } catch (err) {
      toast.error(apiErrorMessage(err, t('wf.org.groups.toast.updateFailed')));
      throw err;
    }
  };

  const handleDelete = async () => {
    if (!deleting) return;
    try {
      await organizationService.deleteGroup(deleting.id);
      toast.success(t('wf.org.groups.toast.deleted'));
      setDeleting(null);
      fetchGroups();
    } catch (err) {
      toast.error(apiErrorMessage(err, t('wf.org.groups.toast.deleteFailed')));
    }
  };

  const filteredGroups = groups.filter(
    (g) =>
      g.name.toLowerCase().includes(search.toLowerCase()) ||
      g.code.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div>
      <PageHeader
        title={t('wf.org.groups.title')}
        description={t('wf.org.groups.description')}
        actions={
          <>
            <Button variant="outline" size="sm" onClick={fetchGroups}>
              <RefreshCw size={16} className="mr-2" /> {t('common.refresh')}
            </Button>
            <Button size="sm" onClick={() => setShowCreate(true)}>
              <Plus size={16} className="mr-2" /> {t('wf.org.groups.add')}
            </Button>
          </>
        }
      />

      <div className="relative mb-4">
        <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
        <Input placeholder={t('wf.org.groups.searchPlaceholder')} value={search} onChange={(e) => setSearch(e.target.value)} className="pl-9 h-9 max-w-xs" />
      </div>

      <div className="table-container">
        <table className="w-full">
          <thead className="table-header">
            <tr>
              <th className="text-left text-xs font-medium text-muted-foreground uppercase tracking-wider px-4 py-3">{t('wf.org.groups.form.name')}</th>
              <th className="text-left text-xs font-medium text-muted-foreground uppercase tracking-wider px-4 py-3">{t('wf.common.code')}</th>
              <th className="text-center text-xs font-medium text-muted-foreground uppercase tracking-wider px-4 py-3">{t('wf.org.groups.table.companies')}</th>
              <th className="text-center text-xs font-medium text-muted-foreground uppercase tracking-wider px-4 py-3">{t('wf.common.status')}</th>
              <th className="text-right text-xs font-medium text-muted-foreground uppercase tracking-wider px-4 py-3">{t('wf.common.actions')}</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {loading ? (
              <tr><td colSpan={5} className="text-center py-12 text-sm text-muted-foreground">{t('common.loading')}</td></tr>
            ) : filteredGroups.length === 0 ? (
              <tr><td colSpan={5} className="text-center py-12">
                <div className="flex flex-col items-center gap-2">
                  <Building2 size={32} className="text-muted-foreground/40" />
                  <p className="text-sm text-muted-foreground">{search ? t('wf.org.groups.empty.filtered') : t('wf.org.groups.empty.default')}</p>
                </div>
              </td></tr>
            ) : (
              filteredGroups.map((group) => (
                <tr key={group.id} className="table-row-hover">
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-md bg-primary/10 flex items-center justify-center">
                        <Building2 size={16} className="text-primary" />
                      </div>
                      <div>
                        <p className="text-sm font-medium">{group.name}</p>
                        <p className="text-xs text-muted-foreground">{t('employees.detail.career.createdAt', { date: formatDate(group.createdAt) })}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-4 py-3"><span className="text-sm font-mono text-muted-foreground">{group.code}</span></td>
                  <td className="px-4 py-3 text-center text-sm">{group._count?.companies || 0}</td>
                  <td className="px-4 py-3 text-center">
                    <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-400">{group.status}</span>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <div className="flex items-center justify-end gap-1">
                      <button onClick={() => setEditing(group)} className="p-1.5 rounded-lg hover:bg-muted text-muted-foreground hover:text-foreground" title={t('common.edit')}><Pencil size={15} /></button>
                      <button onClick={() => setDeleting(group)} className="p-1.5 rounded-lg hover:bg-red-50 text-muted-foreground hover:text-red-600" title={t('common.delete')}><Trash2 size={15} /></button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <Modal open={showCreate} onClose={() => setShowCreate(false)} title={t('wf.org.groups.modal.create')}><GroupForm onSave={handleCreate} onClose={() => setShowCreate(false)} /></Modal>
      <Modal open={!!editing} onClose={() => setEditing(null)} title={t('wf.org.groups.modal.edit')}>{editing && <GroupForm initial={editing} onSave={handleUpdate} onClose={() => setEditing(null)} />}</Modal>
      <ConfirmDialog open={!!deleting} onClose={() => setDeleting(null)} onConfirm={handleDelete} title={t('wf.org.groups.confirm.title')} message={t('wf.org.confirm.deleteMessagePermanent', { name: deleting?.name ?? '' })} />
    </div>
  );
}
