import { departmentRepository } from '../repositories/department.repository';
import { eventBus } from '@/shared/events/EventBus';
import { DomainEvents } from '@/shared/events/events';
import { WinstonLogger } from '@/shared/logger/WinstonLogger';
import { NotFoundError, ConflictError, ValidationError } from '@/shared/exceptions/AppError';
import { CreateDepartmentDTO, UpdateDepartmentDTO } from '../organization.dto';
import { randomUUID as uuidv4 } from 'node:crypto';
import { generateSystemCode } from '@/shared/utils/system-code';
import { assertNoActiveDependents, assertNoDepartmentCycle, assertOrgRefsInCompany } from '../org-integrity';

const logger = new WinstonLogger('DepartmentService');

export class DepartmentService {
  async findAll(companyId: string, divisionId?: string) {
    return departmentRepository.findAll(companyId, divisionId);
  }

  async findById(id: string) {
    const dept = await departmentRepository.findById(id);
    if (!dept) throw new NotFoundError('Department not found');
    return dept;
  }

  async create(dto: CreateDepartmentDTO) {
    const code = await generateSystemCode({
      prefix: 'DPT',
      label: dto.name,
      exists: async (candidate) => Boolean(await departmentRepository.findByCode(candidate)),
    });
    const existing = await departmentRepository.findByCode(code);
    if (existing) throw new ConflictError(`Department code "${code}" already exists`);

    await assertOrgRefsInCompany(dto.companyId, { divisionId: dto.divisionId, parentId: dto.parentId, headId: dto.headId });
    const dept = await departmentRepository.create({ ...dto, code });

    await eventBus.publish({
      name: DomainEvents.DEPARTMENT_CREATED,
      aggregateId: dept.id,
      aggregateType: 'Department',
      data: dto,
      metadata: { eventId: uuidv4(), occurredAt: new Date() },
    });

    return dept;
  }

  async update(id: string, dto: UpdateDepartmentDTO) {
    const current = await this.findById(id);
    if (dto.code && dto.code !== current.code) {
      throw new ValidationError('Department code is generated by system and cannot be changed');
    }
    if (dto.code === current.code) delete dto.code;

    await assertOrgRefsInCompany(current.companyId, { divisionId: dto.divisionId, parentId: dto.parentId, headId: dto.headId });
    if (dto.parentId) await assertNoDepartmentCycle(id, dto.parentId);

    return departmentRepository.update(id, dto);
  }

  async delete(id: string) {
    const current = await this.findById(id);
    await assertNoActiveDependents([
      { model: 'employee', where: { departmentId: id, companyId: current.companyId }, label: 'karyawan' },
      { model: 'department', where: { parentId: id }, label: 'sub-departemen (child)' },
      { model: 'position', where: { departmentId: id }, label: 'posisi' },
    ]);
    await departmentRepository.softDelete(id);
  }

  async getHierarchy(companyId: string) {
    return departmentRepository.getHierarchy(companyId);
  }
}

export const departmentService = new DepartmentService();
