import { divisionRepository } from '../repositories/division.repository';
import { eventBus } from '@/shared/events/EventBus';
import { DomainEvents } from '@/shared/events/events';
import { WinstonLogger } from '@/shared/logger/WinstonLogger';
import { NotFoundError, ConflictError, ValidationError } from '@/shared/exceptions/AppError';
import { CreateDivisionDTO, UpdateDivisionDTO } from '../organization.dto';
import { v4 as uuidv4 } from 'uuid';
import { generateSystemCode } from '@/shared/utils/system-code';

const logger = new WinstonLogger('DivisionService');

export class DivisionService {
  async findAll(companyId: string) {
    return divisionRepository.findAll(companyId);
  }

  async findById(id: string) {
    const division = await divisionRepository.findById(id);
    if (!division) throw new NotFoundError('Division not found');
    return division;
  }

  async create(dto: CreateDivisionDTO) {
    const code = await generateSystemCode({
      prefix: 'DIV',
      label: dto.name,
      exists: async (candidate) => Boolean(await divisionRepository.findByCode(candidate)),
    });
    const existing = await divisionRepository.findByCode(code);
    if (existing) throw new ConflictError(`Division code "${code}" already exists`);

    const division = await divisionRepository.create({ ...dto, code });

    await eventBus.publish({
      name: DomainEvents.DIVISION_CREATED,
      aggregateId: division.id,
      aggregateType: 'Division',
      data: dto,
      metadata: { eventId: uuidv4(), occurredAt: new Date() },
    });

    return division;
  }

  async update(id: string, dto: UpdateDivisionDTO) {
    const current = await this.findById(id);
    if (dto.code && dto.code !== current.code) {
      throw new ValidationError('Division code is generated by system and cannot be changed');
    }
    if (dto.code === current.code) delete dto.code;

    return divisionRepository.update(id, dto);
  }

  async delete(id: string) {
    await this.findById(id);
    await divisionRepository.softDelete(id);
  }
}

export const divisionService = new DivisionService();
