import { positionRepository } from '../repositories/position.repository';
import { eventBus } from '@/shared/events/EventBus';
import { DomainEvents } from '@/shared/events/events';
import { WinstonLogger } from '@/shared/logger/WinstonLogger';
import { NotFoundError, ConflictError, ValidationError } from '@/shared/exceptions/AppError';
import { CreatePositionDTO, UpdatePositionDTO } from '../organization.dto';
import { v4 as uuidv4 } from 'uuid';
import { generateSystemCode } from '@/shared/utils/system-code';

const logger = new WinstonLogger('PositionService');

export class PositionService {
  async findAll(companyId: string, departmentId?: string) {
    return positionRepository.findAll(companyId, departmentId);
  }

  async findById(id: string) {
    const position = await positionRepository.findById(id);
    if (!position) throw new NotFoundError('Position not found');
    return position;
  }

  async create(dto: CreatePositionDTO) {
    const code = await generateSystemCode({
      prefix: 'POS',
      label: dto.name,
      exists: async (candidate) => Boolean(await positionRepository.findByCode(candidate)),
    });
    const existing = await positionRepository.findByCode(code);
    if (existing) throw new ConflictError(`Position code "${code}" already exists`);

    const position = await positionRepository.create({ ...dto, code });

    await eventBus.publish({
      name: DomainEvents.POSITION_CREATED,
      aggregateId: position.id,
      aggregateType: 'Position',
      data: dto,
      metadata: { eventId: uuidv4(), occurredAt: new Date() },
    });

    return position;
  }

  async update(id: string, dto: UpdatePositionDTO) {
    const current = await this.findById(id);
    if (dto.code && dto.code !== current.code) {
      throw new ValidationError('Position code is generated by system and cannot be changed');
    }
    if (dto.code === current.code) delete dto.code;

    return positionRepository.update(id, dto);
  }

  async delete(id: string) {
    await this.findById(id);
    await positionRepository.softDelete(id);
  }
}

export const positionService = new PositionService();
