import { subDepartmentRepository } from '../repositories/sub-department.repository';
import { NotFoundError, ConflictError, ValidationError } from '@/shared/exceptions/AppError';
import { CreateSubDepartmentDTO, UpdateSubDepartmentDTO } from '../organization.dto';
import { generateSystemCode } from '@/shared/utils/system-code';

export class SubDepartmentService {
  async findAll(departmentId: string) {
    return subDepartmentRepository.findAll(departmentId);
  }

  async findById(id: string) {
    const sub = await subDepartmentRepository.findById(id);
    if (!sub) throw new NotFoundError('Sub-department not found');
    return sub;
  }

  async create(dto: CreateSubDepartmentDTO) {
    const code = await generateSystemCode({
      prefix: 'SUBDPT',
      label: dto.name,
      exists: async (candidate) => Boolean(await subDepartmentRepository.findByCode(candidate)),
    });
    const existing = await subDepartmentRepository.findByCode(code);
    if (existing) throw new ConflictError(`Sub-department code "${code}" already exists`);
    return subDepartmentRepository.create({ ...dto, code });
  }

  async update(id: string, dto: UpdateSubDepartmentDTO) {
    const current = await this.findById(id);
    if (dto.code && dto.code !== current.code) {
      throw new ValidationError('Sub-department code is generated by system and cannot be changed');
    }
    if (dto.code === current.code) delete dto.code;
    return subDepartmentRepository.update(id, dto);
  }

  async delete(id: string) {
    await this.findById(id);
    await subDepartmentRepository.softDelete(id);
  }
}

export const subDepartmentService = new SubDepartmentService();
