import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { PageHeader } from '@/components/shared/PageHeader';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select2 } from '@/components/ui/select2';
import { useI18n } from '@/i18n/provider';
import { useCompanyStore } from '@/stores/company.store';
import { organizationService, type Department, type Position } from '@/services/organization.service';
import { recruitmentService, type JobPostingPayload } from '@/services/recruitment.service';
import toast from 'react-hot-toast';
import { ArrowLeft } from 'lucide-react';
import { apiErrorMessage } from '@/lib/errors';

const EMPLOYMENT_TYPE_OPTIONS = [
  { value: 'FULL_TIME', label: 'FULL_TIME' },
  { value: 'PART_TIME', label: 'PART_TIME' },
  { value: 'CONTRACT', label: 'CONTRACT' },
  { value: 'INTERNSHIP', label: 'INTERNSHIP' },
  { value: 'FREELANCE', label: 'FREELANCE' },
];

export function JobPostingFormPage() {
  const { t } = useI18n();
  const navigate = useNavigate();
  const { activeCompany } = useCompanyStore();
  const [departments, setDepartments] = useState<Department[]>([]);
  const [positions, setPositions] = useState<Position[]>([]);
  const [loading, setLoading] = useState(false);
  const companyId = activeCompany?.id || '';
  const [form, setForm] = useState<JobPostingPayload>({
    companyId,
    departmentId: undefined,
    positionId: undefined,
    title: '',
    code: '',
    employmentType: 'FULL_TIME',
    location: '',
    minSalary: undefined,
    maxSalary: undefined,
    currency: 'IDR',
    description: '',
    requirements: '',
    responsibilities: '',
    vacancies: 1,
  });

  useEffect(() => {
    setForm((prev) => ({ ...prev, companyId }));
  }, [companyId]);

  useEffect(() => {
    if (!companyId) return;

    const loadReferences = async () => {
      try {
        const [departmentData, positionData] = await Promise.all([
          organizationService.getDepartments(companyId),
          organizationService.getPositions(companyId),
        ]);
        setDepartments(departmentData);
        setPositions(positionData);
      } catch (error) {
        console.error(error);
        toast.error(t('wf.rec.postingForm.loadRefsFailed'));
      }
    };

    void loadReferences();
  }, [companyId, t]);

  const handleSubmit = useCallback(async () => {
    if (!companyId) {
      toast.error(t('wf.rec.noActiveCompany'));
      return;
    }

    if (!form.title.trim()) {
      toast.error(t('wf.rec.postingForm.titleRequired'));
      return;
    }

    if (form.maxSalary !== undefined && form.minSalary !== undefined && form.maxSalary < form.minSalary) {
      toast.error(t('wf.rec.postingForm.salaryInvalid'));
      return;
    }

    setLoading(true);
    try {
      const payload: JobPostingPayload = {
        ...form,
        companyId,
        code: undefined,
        departmentId: form.departmentId || undefined,
        positionId: form.positionId || undefined,
        location: form.location?.trim() || undefined,
        currency: form.currency?.trim() || 'IDR',
        description: form.description?.trim() || undefined,
        requirements: form.requirements?.trim() || undefined,
        responsibilities: form.responsibilities?.trim() || undefined,
      };

      const created = await recruitmentService.createJobPosting(payload);
      toast.success(t('wf.rec.postingForm.createSuccess'));
      navigate(`/recruitment/postings/${created.id}`);
    } catch (error) {
      console.error(error);
      toast.error(apiErrorMessage(error, t('wf.rec.postingForm.createFailed')));
    } finally {
      setLoading(false);
    }
  }, [companyId, form, navigate, t]);

  return (
    <div>
      <PageHeader
        title={t('wf.rec.postingForm.title')}
        description={t('wf.rec.postingForm.description')}
        actions={(
          <Button variant="outline" size="sm" onClick={() => navigate('/recruitment')}>
            <ArrowLeft size={16} className="mr-2" />
            {t('employees.detail.actions.back')}
          </Button>
        )}
      />

      <div className="rounded-xl border border-border bg-card p-5">
        <div className="grid gap-4 md:grid-cols-2">
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('wf.rec.postingForm.fields.title')}</label>
            <Input value={form.title} onChange={(e) => setForm((prev) => ({ ...prev, title: e.target.value }))} placeholder={t('wf.rec.postingForm.titlePlaceholder')} />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('wf.common.code')}</label>
            <Input value="" placeholder={t('wf.common.autoGenerated')} disabled />
            <p className="text-xs text-muted-foreground">{t('wf.rec.postingForm.codeHint')}</p>
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('employees.detail.fields.department')}</label>
            <Select2
              value={form.departmentId || ''}
              onValueChange={(value) => setForm((prev) => ({ ...prev, departmentId: value || undefined }))}
              options={[{ value: '', label: t('employees.detail.dialog.noDepartment') }, ...departments.map((item) => ({ value: item.id, label: item.name }))]}
              placeholder={t('employees.detail.dialog.selectDepartment')}
            />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('employees.detail.fields.position')}</label>
            <Select2
              value={form.positionId || ''}
              onValueChange={(value) => setForm((prev) => ({ ...prev, positionId: value || undefined }))}
              options={[{ value: '', label: t('employees.detail.dialog.noPosition') }, ...positions.map((item) => ({ value: item.id, label: item.name }))]}
              placeholder={t('employees.detail.dialog.selectPosition')}
            />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('employees.detail.fields.employmentType')}</label>
            <Select2
              value={form.employmentType}
              onValueChange={(value) => setForm((prev) => ({ ...prev, employmentType: value }))}
              options={EMPLOYMENT_TYPE_OPTIONS}
              placeholder={t('wf.rec.postingForm.selectType')}
            />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('wf.common.location')}</label>
            <Input value={form.location || ''} onChange={(e) => setForm((prev) => ({ ...prev, location: e.target.value }))} placeholder={t('wf.rec.postingForm.locationPlaceholder')} />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('wf.rec.postingDetail.vacancies')}</label>
            <Input type="number" min={1} value={String(form.vacancies)} onChange={(e) => setForm((prev) => ({ ...prev, vacancies: Number(e.target.value || 1) }))} />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('wf.rec.postingForm.currency')}</label>
            <Input value={form.currency || 'IDR'} onChange={(e) => setForm((prev) => ({ ...prev, currency: e.target.value.toUpperCase() }))} placeholder="IDR" />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('wf.rec.postingForm.minSalary')}</label>
            <Input type="number" min={0} value={form.minSalary ?? ''} onChange={(e) => setForm((prev) => ({ ...prev, minSalary: e.target.value ? Number(e.target.value) : undefined }))} placeholder="10000000" />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('wf.rec.postingForm.maxSalary')}</label>
            <Input type="number" min={0} value={form.maxSalary ?? ''} onChange={(e) => setForm((prev) => ({ ...prev, maxSalary: e.target.value ? Number(e.target.value) : undefined }))} placeholder="15000000" />
          </div>
        </div>

        <div className="mt-4 space-y-4">
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('wf.common.description')}</label>
            <textarea
              value={form.description || ''}
              onChange={(e) => setForm((prev) => ({ ...prev, description: e.target.value }))}
              className="min-h-28 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm"
              placeholder={t('wf.rec.postingForm.descriptionPlaceholder')}
            />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('wf.rec.postingDetail.requirements')}</label>
            <textarea
              value={form.requirements || ''}
              onChange={(e) => setForm((prev) => ({ ...prev, requirements: e.target.value }))}
              className="min-h-28 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm"
              placeholder={t('wf.rec.postingForm.requirementsPlaceholder')}
            />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{t('wf.rec.postingForm.responsibilities')}</label>
            <textarea
              value={form.responsibilities || ''}
              onChange={(e) => setForm((prev) => ({ ...prev, responsibilities: e.target.value }))}
              className="min-h-28 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm"
              placeholder={t('wf.rec.postingForm.responsibilitiesPlaceholder')}
            />
          </div>
        </div>

        <div className="mt-5 flex justify-end gap-2">
          <Button variant="outline" size="sm" onClick={() => navigate('/recruitment')}>
            {t('common.cancel')}
          </Button>
          <Button size="sm" onClick={handleSubmit} disabled={loading}>
            {loading ? t('wf.common.saving') : t('wf.rec.postingForm.submit')}
          </Button>
        </div>
      </div>
    </div>
  );
}
