export enum EmployeeStatus {
  ACTIVE = 'ACTIVE',
  RESIGNED = 'RESIGNED',
  TERMINATED = 'TERMINATED',
  PROBATION = 'PROBATION',
  CONTRACT_END = 'CONTRACT_END',
}

export enum EmploymentType {
  PERMANENT = 'PERMANENT',
  CONTRACT = 'CONTRACT',
  INTERN = 'INTERN',
  PROBATION = 'PROBATION',
  FREELANCE = 'FREELANCE',
  OUTSOURCING = 'OUTSOURCING',
}
