import { parse } from 'csv-parse/sync';
import { employeeRepository } from './employee.repository';
import {
  CreateEmployeeDTO, UpdateEmployeeDTO, EmployeeQueryDTO, CreateCareerTransactionDTO, createEmployeeSchema,
  CreateEmployeeCompanyAssignmentDTO, UpdateEmployeeCompanyAssignmentDTO,
  CreateEmployeeFamilyDTO, UpdateEmployeeFamilyDTO,
  CreateEmployeeEducationDTO, UpdateEmployeeEducationDTO,
  CreateEmployeeEmergencyContactDTO, UpdateEmployeeEmergencyContactDTO,
  CreateEmployeeTrainingDTO, UpdateEmployeeTrainingDTO,
  CreateEmployeeSkillDTO, UpdateEmployeeSkillDTO,
  CreateEmployeeExperienceDTO, UpdateEmployeeExperienceDTO,
  CreateEmployeeAttachmentDTO, UpdateEmployeeAttachmentDTO,
} from './employee.dto';
import { NotFoundError, ConflictError, BadRequestError, ValidationError } from '@/shared/exceptions/AppError';
import { logger } from '@/shared/logger/WinstonLogger';
import { prisma } from '@/shared/database/prisma';
import { generateSystemCode } from '@/shared/utils/system-code';

export class EmployeeService {
  async findAll(query: EmployeeQueryDTO) {
    return employeeRepository.findAll(query);
  }

  async findById(id: string) {
    const employee = await employeeRepository.findById(id);
    if (!employee) throw new NotFoundError('Employee not found');
    return employee;
  }

  // VAL-007: relational date rules. Min working age 15 at join; resignation after join.
  private validateEmployeeDates(dates: {
    dateOfBirth?: string | Date | null;
    joinDate?: string | Date | null;
    resignationDate?: string | Date | null;
  }) {
    const toDate = (v?: string | Date | null) => (v ? new Date(v) : null);
    const dob = toDate(dates.dateOfBirth);
    const join = toDate(dates.joinDate);
    const resign = toDate(dates.resignationDate);

    if (dob && join) {
      const minJoin = new Date(dob);
      minJoin.setFullYear(minJoin.getFullYear() + 15);
      if (join < minJoin) {
        throw new BadRequestError('Usia minimal 15 tahun saat tanggal bergabung');
      }
    }
    if (resign && join && resign <= join) {
      throw new BadRequestError('Tanggal resign harus setelah tanggal bergabung');
    }
  }

  async create(data: CreateEmployeeDTO) {
    this.validateEmployeeDates(data);

    const employeeNumber = await generateSystemCode({
      prefix: 'EMP',
      label: `${data.firstName} ${data.lastName}`,
      exists: async (candidate) => Boolean(await employeeRepository.findByEmployeeNumber(data.companyId, candidate)),
    });

    const existing = await employeeRepository.findByEmployeeNumber(data.companyId, employeeNumber);
    if (existing) throw new ConflictError('Employee number already exists');

    // Check unique email if provided
    if (data.email) {
      const emailExists = await employeeRepository.findByEmail(data.email);
      if (emailExists) throw new ConflictError('Email already in use');
    }

    if (data.employeeCategory === 'FACTORY') {
      if (!data.shiftFormulaId || !data.shiftStartDate) {
        throw new BadRequestError('Pegawai pabrik wajib memiliki shift formula dan tanggal mulai shift');
      }

      const shiftFormula = await prisma.shiftFormula.findFirst({
        where: {
          id: data.shiftFormulaId,
          companyId: data.companyId,
          deletedAt: null,
          isActive: true,
        },
      });

      if (!shiftFormula) {
        throw new BadRequestError('Shift formula tidak ditemukan atau tidak aktif untuk company ini');
      }
    } else {
      data.shiftFormulaId = null;
      data.shiftStartDate = null;
    }

    const employee = await employeeRepository.create({
      ...data,
      employeeNumber,
    });
    logger.info('Employee created', { employeeId: employee.id, number: employee.employeeNumber });
    return employee;
  }

  async update(id: string, data: UpdateEmployeeDTO) {
    const existingEmployee = await this.findById(id);

    const rec = existingEmployee as Record<string, unknown>;
    this.validateEmployeeDates({
      dateOfBirth: (data.dateOfBirth ?? (rec.dateOfBirth as string | Date | null)) ?? null,
      joinDate: (data.joinDate ?? (rec.joinDate as string | Date | null)) ?? null,
      resignationDate: (rec.resignationDate as string | Date | null) ?? null,
    });
    const requestedEmployeeNumber = (data as Record<string, unknown>).employeeNumber;

    if (typeof requestedEmployeeNumber === 'string' && requestedEmployeeNumber !== existingEmployee.employeeNumber) {
      throw new ValidationError('Employee number is generated by system and cannot be changed');
    }

    if (data.email) {
      const emailExists = await employeeRepository.findByEmail(data.email);
      if (emailExists && emailExists.id !== id) {
        throw new ConflictError('Email already in use');
      }
    }

    const nextEmployeeCategory = data.employeeCategory ?? existingEmployee.employeeCategory;
    const nextShiftFormulaId = data.shiftFormulaId !== undefined
      ? data.shiftFormulaId
      : existingEmployee.shiftFormulaId ?? null;
    const nextShiftStartDate = data.shiftStartDate !== undefined
      ? data.shiftStartDate
      : existingEmployee.shiftStartDate
        ? new Date(existingEmployee.shiftStartDate).toISOString()
        : null;

    if (nextEmployeeCategory === 'FACTORY') {
      if (!nextShiftFormulaId || !nextShiftStartDate) {
        throw new BadRequestError('Pegawai pabrik wajib memiliki shift formula dan tanggal mulai shift');
      }

      const shiftFormula = await prisma.shiftFormula.findFirst({
        where: {
          id: nextShiftFormulaId,
          companyId: existingEmployee.companyId,
          deletedAt: null,
          isActive: true,
        },
      });

      if (!shiftFormula) {
        throw new BadRequestError('Shift formula tidak ditemukan atau tidak aktif untuk company ini');
      }
    } else {
      data.shiftFormulaId = null;
      data.shiftStartDate = null;
    }

    const employee = await employeeRepository.update(id, data);
    logger.info('Employee updated', { employeeId: id });
    return employee;
  }

  async delete(id: string) {
    await this.findById(id);
    await employeeRepository.softDelete(id);
    logger.info('Employee deleted', { employeeId: id });
  }

  async updateStatus(id: string, status: string) {
    await this.findById(id);
    const validStatuses = ['ACTIVE', 'RESIGNED', 'TERMINATED', 'PROBATION', 'CONTRACT_END'];
    if (!validStatuses.includes(status)) {
      throw new BadRequestError(`Invalid status: ${status}`);
    }
    return employeeRepository.updateStatus(id, status);
  }

  async findCareerTransactions(employeeId: string) {
    await this.findById(employeeId);
    return employeeRepository.findCareerTransactions(employeeId);
  }

  async createCareerTransaction(employeeId: string, data: CreateCareerTransactionDTO, createdBy?: string) {
    const employee = await this.findById(employeeId);

    if (data.toDepartmentId === employee.departmentId &&
        data.toPositionId === employee.positionId &&
        data.toBranchId === employee.branchId &&
        (data.toEmploymentType === undefined || data.toEmploymentType === employee.employmentType)) {
      throw new BadRequestError('No actual career change detected');
    }

    const transaction = await employeeRepository.createCareerTransaction(employeeId, createdBy, data);

    if (!transaction) {
      throw new NotFoundError('Employee not found');
    }

    logger.info('Employee career transaction created', {
      employeeId,
      transactionType: data.transactionType,
      createdBy,
    });

    return transaction;
  }

  async findCompanyAssignments(employeeId: string) {
    await this.findById(employeeId);
    return employeeRepository.findCompanyAssignments(employeeId);
  }

  async createCompanyAssignment(
    employeeId: string,
    data: CreateEmployeeCompanyAssignmentDTO
  ) {
    const employee = await this.findById(employeeId);

    if (data.assignmentType === 'PRIMARY' && data.companyId !== employee.companyId) {
      throw new BadRequestError('Primary assignment must match the employee primary company');
    }

    if (data.endDate && new Date(data.endDate) < new Date(data.startDate)) {
      throw new BadRequestError('Assignment end date must be after start date');
    }

    return employeeRepository.createCompanyAssignment(employeeId, {
      companyId: data.companyId,
      assignmentType: data.assignmentType,
      startDate: new Date(data.startDate),
      endDate: data.endDate ? new Date(data.endDate) : null,
      reason: data.reason,
      approvedBy: data.approvedBy || null,
    });
  }

  async updateCompanyAssignment(
    employeeId: string,
    assignmentId: string,
    data: UpdateEmployeeCompanyAssignmentDTO
  ) {
    await this.findById(employeeId);

    const current = await employeeRepository.findCompanyAssignmentById(assignmentId);
    if (!current || current.employeeId !== employeeId) {
      throw new NotFoundError('Employee company assignment not found');
    }

    const nextStartDate = data.startDate ? new Date(data.startDate) : current.startDate;
    const nextEndDate =
      data.endDate !== undefined
        ? (data.endDate ? new Date(data.endDate) : null)
        : current.endDate;

    if (nextEndDate && nextEndDate < nextStartDate) {
      throw new BadRequestError('Assignment end date must be after start date');
    }

    return employeeRepository.updateCompanyAssignment(assignmentId, {
      ...(data.companyId !== undefined ? { companyId: data.companyId } : {}),
      ...(data.assignmentType !== undefined ? { assignmentType: data.assignmentType } : {}),
      ...(data.startDate !== undefined ? { startDate: new Date(data.startDate) } : {}),
      ...(data.endDate !== undefined ? { endDate: data.endDate ? new Date(data.endDate) : null } : {}),
      ...(data.reason !== undefined ? { reason: data.reason } : {}),
      ...(data.approvedBy !== undefined ? { approvedBy: data.approvedBy || null } : {}),
    });
  }

  async deleteCompanyAssignment(employeeId: string, assignmentId: string) {
    await this.findById(employeeId);

    const current = await employeeRepository.findCompanyAssignmentById(assignmentId);
    if (!current || current.employeeId !== employeeId) {
      throw new NotFoundError('Employee company assignment not found');
    }

    await employeeRepository.deleteCompanyAssignment(assignmentId);
  }

  // ============================================================
  // Employee Family
  // ============================================================
  async findFamilies(employeeId: string) {
    return employeeRepository.findFamilies(employeeId);
  }

  async createFamily(employeeId: string, data: CreateEmployeeFamilyDTO) {
    return employeeRepository.createFamily(employeeId, data);
  }

  async updateFamily(id: string, data: UpdateEmployeeFamilyDTO) {
    return employeeRepository.updateFamily(id, data);
  }

  async deleteFamily(id: string) {
    return employeeRepository.deleteFamily(id);
  }

  // ============================================================
  // Employee Education
  // ============================================================
  async findEducations(employeeId: string) {
    return employeeRepository.findEducations(employeeId);
  }

  async createEducation(employeeId: string, data: CreateEmployeeEducationDTO) {
    return employeeRepository.createEducation(employeeId, data);
  }

  async updateEducation(id: string, data: UpdateEmployeeEducationDTO) {
    return employeeRepository.updateEducation(id, data);
  }

  async deleteEducation(id: string) {
    return employeeRepository.deleteEducation(id);
  }

  // ============================================================
  // Employee Emergency Contact
  // ============================================================
  async findEmergencyContacts(employeeId: string) {
    return employeeRepository.findEmergencyContacts(employeeId);
  }

  async createEmergencyContact(employeeId: string, data: CreateEmployeeEmergencyContactDTO) {
    return employeeRepository.createEmergencyContact(employeeId, data);
  }

  async updateEmergencyContact(id: string, data: UpdateEmployeeEmergencyContactDTO) {
    return employeeRepository.updateEmergencyContact(id, data);
  }

  async deleteEmergencyContact(id: string) {
    return employeeRepository.deleteEmergencyContact(id);
  }

  // ============================================================
  // Employee Training
  // ============================================================
  async findTrainings(employeeId: string) {
    return employeeRepository.findTrainings(employeeId);
  }

  async createTraining(employeeId: string, data: CreateEmployeeTrainingDTO) {
    return employeeRepository.createTraining(employeeId, data);
  }

  async updateTraining(id: string, data: UpdateEmployeeTrainingDTO) {
    return employeeRepository.updateTraining(id, data);
  }

  async deleteTraining(id: string) {
    return employeeRepository.deleteTraining(id);
  }

  // ============================================================
  // Employee Skill
  // ============================================================
  async findSkills(employeeId: string) {
    return employeeRepository.findSkills(employeeId);
  }

  async createSkill(employeeId: string, data: CreateEmployeeSkillDTO) {
    return employeeRepository.createSkill(employeeId, data);
  }

  async updateSkill(id: string, data: UpdateEmployeeSkillDTO) {
    return employeeRepository.updateSkill(id, data);
  }

  async deleteSkill(id: string) {
    return employeeRepository.deleteSkill(id);
  }

  // ============================================================
  // Employee Experience
  // ============================================================
  async findExperiences(employeeId: string) {
    return employeeRepository.findExperiences(employeeId);
  }

  async createExperience(employeeId: string, data: CreateEmployeeExperienceDTO) {
    return employeeRepository.createExperience(employeeId, data);
  }

  async updateExperience(id: string, data: UpdateEmployeeExperienceDTO) {
    return employeeRepository.updateExperience(id, data);
  }

  async deleteExperience(id: string) {
    return employeeRepository.deleteExperience(id);
  }

  // ============================================================
  // Employee Attachment
  // ============================================================
  async findAttachments(employeeId: string, category?: string) {
    return employeeRepository.findAttachments(employeeId, category);
  }

  async createAttachment(employeeId: string, data: CreateEmployeeAttachmentDTO) {
    return employeeRepository.createAttachment(employeeId, data);
  }

  async updateAttachment(id: string, data: UpdateEmployeeAttachmentDTO) {
    return employeeRepository.updateAttachment(id, data);
  }

  async deleteAttachment(id: string) {
    return employeeRepository.deleteAttachment(id);
  }

  async importCsv(companyId: string, file: Express.Multer.File) {
    const records = parse(file.buffer, {
      columns: true,
      skip_empty_lines: true,
      trim: true,
      relax_column_count: true,
    });

    // Task 2.5 (FTR-004): validate ALL rows in memory first; only if everything
    // is valid do we insert — in a single transaction (all-or-nothing).
    const errors: { row: number; column?: string; value?: unknown; message: string }[] = [];
    const valid: CreateEmployeeDTO[] = [];
    const seenNumbers = new Set<string>();
    const seenEmails = new Set<string>();

    for (let i = 0; i < records.length; i++) {
      const rowIndex = i + 2; // row 1 is the header
      const row = records[i] as Record<string, string>;

      const payload = {
        companyId,
        employeeNumber: row.employeeNumber || row.nik || undefined,
        firstName: row.firstName || row.first_name || '',
        lastName: row.lastName || row.last_name || '',
        email: row.email || undefined,
        phone: row.phone || undefined,
        idNumber: row.idNumber || row.id_number || row.ktp || undefined,
        placeOfBirth: row.placeOfBirth || row.place_of_birth || undefined,
        dateOfBirth: row.dateOfBirth || row.date_of_birth || undefined,
        gender: (row.gender || undefined) as any,
        religion: (row.religion || undefined) as any,
        maritalStatus: (row.maritalStatus || row.marital_status || undefined) as any,
        bloodType: (row.bloodType || row.blood_type || undefined) as any,
        nationality: row.nationality || 'Indonesia',
        address: row.address || undefined,
        joinDate: row.joinDate || row.join_date || undefined,
        employmentType: (row.employmentType || row.employment_type || 'PERMANENT') as any,
        employeeCategory: (row.employeeCategory || row.employee_category || 'OFFICE') as any,
        shiftFormulaId: row.shiftFormulaId || row.shift_formula_id || null,
        shiftStartDate: row.shiftStartDate || row.shift_start_date || null,
        branchId: row.branchId || row.branch_id || undefined,
        departmentId: row.departmentId || row.department_id || undefined,
        subDepartmentId: row.subDepartmentId || row.sub_department_id || undefined,
        positionId: row.positionId || row.position_id || undefined,
        bankName: row.bankName || row.bank_name || undefined,
        bankAccount: row.bankAccount || row.bank_account || undefined,
        bankAccountHolder: row.bankAccountHolder || row.bank_account_holder || undefined,
        taxId: row.taxId || row.tax_id || row.npwp || undefined,
        bpjsKetenagakerjaan: row.bpjsKetenagakerjaan || row.bpjs_ketenagakerjaan || undefined,
        bpjsKesehatan: row.bpjsKesehatan || row.bpjs_kesehatan || undefined,
        avatar: row.avatar || undefined,
      };

      const result = createEmployeeSchema.safeParse(payload);
      if (!result.success) {
        for (const issue of result.error.issues) {
          const col = String(issue.path[0] ?? '');
          errors.push({ row: rowIndex, column: col, value: (payload as any)[col], message: issue.message });
        }
        continue;
      }

      const dto = result.data;
      // Business checks that don't need the DB (age/resign, in-file duplicates).
      try {
        this.validateEmployeeDates(dto);
      } catch (err: any) {
        errors.push({ row: rowIndex, column: 'joinDate', value: dto.joinDate, message: err?.message });
        continue;
      }
      if (dto.employeeNumber) {
        if (seenNumbers.has(dto.employeeNumber)) {
          errors.push({ row: rowIndex, column: 'employeeNumber', value: dto.employeeNumber, message: 'employeeNumber duplikat di dalam file' });
          continue;
        }
        seenNumbers.add(dto.employeeNumber);
      }
      if (dto.email) {
        if (seenEmails.has(dto.email)) {
          errors.push({ row: rowIndex, column: 'email', value: dto.email, message: 'Email duplikat di dalam file' });
          continue;
        }
        seenEmails.add(dto.email);
      }
      valid.push(dto);
    }

    // Any error → insert nothing, return a structured report.
    if (errors.length > 0) {
      logger.warn('CSV import rejected', { totalRows: records.length, invalidCount: records.length - valid.length });
      return {
        totalRows: records.length,
        validCount: valid.length,
        invalidCount: records.length - valid.length,
        inserted: 0,
        errors,
      };
    }

    // All valid → one transaction.
    await prisma.$transaction(async (tx) => {
      for (const dto of valid) {
        const employeeNumber = dto.employeeNumber
          || await generateSystemCode({
            prefix: 'EMP',
            label: `${dto.firstName} ${dto.lastName}`,
            exists: async (candidate) =>
              Boolean(await tx.employee.findFirst({ where: { companyId, employeeNumber: candidate } })),
          });
        await tx.employee.create({
          data: {
            ...dto,
            employeeNumber,
            fullName: `${dto.firstName} ${dto.lastName}`,
            dateOfBirth: dto.dateOfBirth ? new Date(dto.dateOfBirth) : undefined,
            joinDate: dto.joinDate ? new Date(dto.joinDate) : undefined,
            shiftStartDate: dto.shiftStartDate ? new Date(dto.shiftStartDate) : undefined,
          },
        });
      }
    }, { timeout: 120_000 });

    logger.info('CSV import completed', { totalRows: records.length, inserted: valid.length });
    return {
      totalRows: records.length,
      validCount: valid.length,
      invalidCount: 0,
      inserted: valid.length,
      errors: [],
    };
  }

  async exportCsv(companyId: string) {
    const { data: employees } = await this.findAll({
      companyId,
      page: 1,
      limit: 99999,
    });

    const headers = [
      'employeeNumber',
      'firstName',
      'lastName',
      'fullName',
      'email',
      'phone',
      'gender',
      'religion',
      'maritalStatus',
      'bloodType',
      'nationality',
      'idNumber',
      'placeOfBirth',
      'dateOfBirth',
      'address',
      'employmentType',
      'joinDate',
      'department',
      'position',
      'branch',
      'bankName',
      'bankAccount',
      'bankAccountHolder',
      'taxId',
      'bpjsKetenagakerjaan',
      'bpjsKesehatan',
      'employmentStatus',
    ];

    const csvEscape = (val: any): string => {
      const str = val == null ? '' : String(val);
      if (str.includes(',') || str.includes('"') || str.includes('\n')) {
        return `"${str.replace(/"/g, '""')}"`;
      }
      return str;
    };

    const rows = employees.map((emp: any) =>
      [
        emp.employeeNumber,
        emp.firstName,
        emp.lastName,
        emp.fullName,
        emp.email,
        emp.phone,
        emp.gender,
        emp.religion,
        emp.maritalStatus,
        emp.bloodType,
        emp.nationality,
        emp.idNumber,
        emp.placeOfBirth,
        emp.dateOfBirth ? new Date(emp.dateOfBirth).toISOString().split('T')[0] : '',
        emp.address,
        emp.employmentType,
        emp.joinDate ? new Date(emp.joinDate).toISOString().split('T')[0] : '',
        emp.department?.name || '',
        emp.position?.name || '',
        emp.branch?.name || '',
        emp.bankName,
        emp.bankAccount,
        emp.bankAccountHolder,
        emp.taxId,
        emp.bpjsKetenagakerjaan,
        emp.bpjsKesehatan,
        emp.employmentStatus,
      ].map(csvEscape).join(',')
    );

    return [headers.join(','), ...rows].join('\n');
  }
}

export const employeeService = new EmployeeService();
