import { payrollRepository } from './payroll.repository';
import {
  CreateSalaryComponentDTO,
  UpdateSalaryComponentDTO,
  CreateEmployeeSalaryDTO,
  UpdateEmployeeSalaryDTO,
  CreatePayrollPeriodDTO,
  UpdatePayrollPeriodDTO,
  CreatePayrollRunDTO,
  CalculatePph21DTO,
  CalculateThrStandaloneDTO,
  CalculateBpjsDTO,
  CalculateJknDTO,
} from './payroll.dto';
import { eventBus } from '@/shared/events/EventBus';
import { DomainEvents } from '@/shared/events/events';
import { logger } from '@/shared/logger/WinstonLogger';
import { NotFoundError, ConflictError, BadRequestError, ValidationError } from '@/shared/exceptions/AppError';
import { v4 as uuidv4 } from 'uuid';
import { employeeLoanRepository } from '@/modules/employee-loan/employee-loan.repository';
import { generateSystemCode } from '@/shared/utils/system-code';
import { calculateBpjs } from '@/shared/payroll/bpjs';
import { calculatePph21 } from '@/shared/payroll/pph21';
import { calculateThr } from '@/shared/payroll/thr';
import { buildPayslipBreakdown } from '@/shared/payroll/payslip-breakdown';
import { groupPayslipsByBank, generateBankCsv, resolveEmployeeBankInfo } from '@/shared/payroll/disbursement';
import type { EmployeeForDisbursement } from '@/shared/payroll/disbursement';
import { prisma } from '@/shared/database/prisma';
import { calculateOvertimePay } from '@/shared/attendance/overtime';
import { workCalendarRepository } from '@/modules/work-calendar/work-calendar.repository';
import { companySettingsService } from '@/modules/company-settings/company-settings.service';
import { JKKRiskClass } from '@prisma/client';
import { ewaRepository } from '@/modules/ewa/ewa.repository';
import { ewaService } from '@/modules/ewa/ewa.service';

const JKK_RISK_TO_RATE: Record<JKKRiskClass, number> = {
  [JKKRiskClass.I]: 0.24,
  [JKKRiskClass.II]: 0.54,
  [JKKRiskClass.III]: 0.89,
  [JKKRiskClass.IV]: 1.27,
  [JKKRiskClass.V]: 1.74,
};

export class PayrollService {
  // ==================== Salary Components ====================

  async findAllSalaryComponents(companyId: string) {
    return payrollRepository.findAllSalaryComponents(companyId);
  }

  async findSalaryComponentById(id: string) {
    const component = await payrollRepository.findSalaryComponentById(id);
    if (!component) throw new NotFoundError('Salary component not found');
    return component;
  }

  async createSalaryComponent(data: CreateSalaryComponentDTO) {
    if (data.calculationMethod === 'FORMULA') {
      throw new BadRequestError(
        'Fitur Formula perhitungan salary component coming soon. Silakan gunakan metode FIXED_AMOUNT atau manfaatkan 4 auto components (OVERTIME_EARNING_AUTO / LATE_DEDUCTION_AUTO / ABSENCE_DEDUCTION_AUTO / LOAN_DEDUCTION_AUTO) untuk kebutuhan standard saat ini.',
      );
    }
    const code = await generateSystemCode({
      prefix: 'PAY-CMP',
      label: data.name,
      exists: async (candidate) => Boolean(await payrollRepository.findSalaryComponentByCode(data.companyId, candidate)),
    });
    const existing = await payrollRepository.findSalaryComponentByCode(data.companyId, code);
    if (existing) throw new ConflictError('Salary component code already exists');

    const component = await payrollRepository.createSalaryComponent({ ...data, code });

    logger.info('Salary component created', { componentId: component.id, code: component.code });
    return component;
  }

  async updateSalaryComponent(id: string, data: UpdateSalaryComponentDTO) {
    const currentComponent = await this.findSalaryComponentById(id);
    if (data.calculationMethod === 'FORMULA') {
      throw new BadRequestError(
        'Fitur Formula perhitungan salary component coming soon. Silakan gunakan metode FIXED_AMOUNT atau manfaatkan 4 auto components (OVERTIME_EARNING_AUTO / LATE_DEDUCTION_AUTO / ABSENCE_DEDUCTION_AUTO / LOAN_DEDUCTION_AUTO) untuk kebutuhan standard saat ini.',
      );
    }
    const requestedCode = (data as Record<string, unknown>).code;
    if (typeof requestedCode === 'string' && requestedCode !== currentComponent.code) {
      throw new ValidationError('Salary component code is generated by system and cannot be changed');
    }
    const component = await payrollRepository.updateSalaryComponent(id, data);

    logger.info('Salary component updated', { componentId: id });
    return component;
  }

  async deleteSalaryComponent(id: string) {
    await this.findSalaryComponentById(id);
    await payrollRepository.softDeleteSalaryComponent(id);

    logger.info('Salary component deleted', { componentId: id });
  }

  // ==================== Employee Salaries ====================

  async findAllEmployeeSalaries(companyId: string, employeeId?: string) {
    return payrollRepository.findAllEmployeeSalaries(companyId, employeeId);
  }

  async findEmployeeSalaryById(id: string) {
    const salary = await payrollRepository.findEmployeeSalaryById(id);
    if (!salary) throw new NotFoundError('Employee salary not found');
    return salary;
  }

  async createEmployeeSalary(data: CreateEmployeeSalaryDTO) {
    // Deactivate existing active salary if any
    const existing = await payrollRepository.findActiveEmployeeSalary(data.employeeId);
    if (existing) {
      await payrollRepository.updateEmployeeSalary(existing.id, { isActive: false });
    }

    const salary = await payrollRepository.createEmployeeSalary(data);

    logger.info('Employee salary created', {
      employeeId: data.employeeId,
      salaryId: salary.id,
    });

    return salary;
  }

  async updateEmployeeSalary(id: string, data: UpdateEmployeeSalaryDTO) {
    await this.findEmployeeSalaryById(id);
    return payrollRepository.updateEmployeeSalary(id, data);
  }

  /**
   * Hitung THR seorang karyawan (Business Rule Gap: Permenaker 6/2016).
   * ≥12 bulan = 1× upah; 1–<12 bulan = prorata (masa kerja/12 × upah); <1 bulan = tidak berhak.
   */
  async calculateEmployeeThr(employeeId: string, referenceDate?: Date) {
    const { salary, employee } = await payrollRepository.findThrInputs(employeeId);
    if (!employee) throw new NotFoundError('Employee not found');
    if (!employee.joinDate) {
      throw new BadRequestError('Tanggal masuk (joinDate) karyawan belum diisi');
    }
    if (!salary) {
      throw new BadRequestError('Data gaji aktif karyawan tidak ditemukan');
    }

    const result = calculateThr({
      monthlyWage: Number(salary.baseSalary),
      joinDate: employee.joinDate,
      referenceDate: referenceDate ?? new Date(),
    });

    logger.info('THR calculated', { employeeId, tenureMonths: result.tenureMonths, amount: result.amount });

    return {
      employee: { id: employee.id, fullName: employee.fullName, employeeNumber: employee.employeeNumber },
      monthlyWage: Number(salary.baseSalary),
      ...result,
    };
  }

  // ==================== Payroll Periods ====================

  async findAllPayrollPeriods(companyId: string) {
    return payrollRepository.findAllPayrollPeriods(companyId);
  }

  async findPayrollPeriodById(id: string) {
    const period = await payrollRepository.findPayrollPeriodById(id);
    if (!period) throw new NotFoundError('Payroll period not found');
    return period;
  }

  async createPayrollPeriod(data: CreatePayrollPeriodDTO) {
    const code = await generateSystemCode({
      prefix: 'PAY-PRD',
      label: data.name,
      exists: async (candidate) => {
        const periods = await payrollRepository.findAllPayrollPeriods(data.companyId);
        return periods.some((period) => period.code === candidate);
      },
    });
    const period = await payrollRepository.createPayrollPeriod({ ...data, code });

    logger.info('Payroll period created', { periodId: period.id, code: period.code });
    return period;
  }

  async closePayrollPeriod(id: string) {
    await this.findPayrollPeriodById(id);
    const period = await payrollRepository.closePayrollPeriod(id);

    logger.info('Payroll period closed', { periodId: id });
    return period;
  }

  async updatePayrollPeriod(id: string, data: UpdatePayrollPeriodDTO) {
    const period = await this.findPayrollPeriodById(id);
    const requestedCode = (data as Record<string, unknown>).code;
    if (typeof requestedCode === 'string' && requestedCode !== period.code) {
      throw new ValidationError('Payroll period code is generated by system and cannot be changed');
    }
    if (period.status === 'CLOSED') {
      throw new BadRequestError('Cannot update a closed payroll period');
    }
    return payrollRepository.updatePayrollPeriod(id, data);
  }

  // ==================== Payroll Runs ====================

  async findAllPayrollRuns(companyId: string) {
    return payrollRepository.findAllPayrollRuns(companyId);
  }

  async findPayrollRunById(id: string) {
    const run = await payrollRepository.findPayrollRunById(id);
    if (!run) throw new NotFoundError('Payroll run not found');
    return run;
  }

  async getAttendanceSummaryForPeriod(periodId: string) {
    const period = await this.findPayrollPeriodById(periodId);
    const periodStart = new Date(period.startDate);
    const periodEnd = new Date(period.endDate);

    const [attendanceGroups, approvedLeaves, overtimes] = await Promise.all([
      prisma.attendance.groupBy({
        by: ['employeeId', 'status'],
        where: { companyId: period.companyId, date: { gte: periodStart, lte: periodEnd }, deletedAt: null },
        _count: { id: true },
      }),
      prisma.leaveRequest.findMany({
        where: {
          companyId: period.companyId, status: 'APPROVED', deletedAt: null,
          OR: [
            { startDate: { gte: periodStart, lte: periodEnd } },
            { endDate: { gte: periodStart, lte: periodEnd } },
            { startDate: { lte: periodStart }, endDate: { gte: periodEnd } },
          ],
        },
        select: { employeeId: true, totalDays: true },
      }),
      prisma.overtimeRequest.findMany({
        where: { companyId: period.companyId, status: 'APPROVED', date: { gte: periodStart, lte: periodEnd }, deletedAt: null },
        select: { employeeId: true, durationHours: true },
      }),
    ]);

    const summary: Record<string, { present: number; absent: number; leave: number; overtime: number }> = {};
    for (const row of attendanceGroups) {
      if (!summary[row.employeeId]) summary[row.employeeId] = { present: 0, absent: 0, leave: 0, overtime: 0 };
      if (row.status === 'PRESENT' || row.status === 'LATE') summary[row.employeeId].present += row._count.id;
      else if (row.status === 'ABSENT') summary[row.employeeId].absent += row._count.id;
    }
    for (const lr of approvedLeaves) {
      if (!summary[lr.employeeId]) summary[lr.employeeId] = { present: 0, absent: 0, leave: 0, overtime: 0 };
      summary[lr.employeeId].leave += lr.totalDays;
    }
    for (const ot of overtimes) {
      if (!summary[ot.employeeId]) summary[ot.employeeId] = { present: 0, absent: 0, leave: 0, overtime: 0 };
      summary[ot.employeeId].overtime += Number(ot.durationHours);
    }

    return { period, attendanceReviewedAt: period.attendanceReviewedAt, summary };
  }

  async confirmAttendanceReview(periodId: string, userId: string) {
    const period = await this.findPayrollPeriodById(periodId);
    if (period.status === 'CLOSED') throw new BadRequestError('Period sudah ditutup');
    return payrollRepository.confirmAttendanceReview(periodId, userId);
  }

  async createPayrollRun(data: CreatePayrollRunDTO, userId?: string) {
    // Validate period exists and is not closed
    const period = await this.findPayrollPeriodById(data.periodId);
    if (period.status === 'CLOSED') {
      throw new BadRequestError('Cannot create payroll run for a closed period');
    }
    if (!period.attendanceReviewedAt) {
      throw new BadRequestError('Attendance harus dikonfirmasi terlebih dahulu sebelum payroll run bisa dieksekusi. Gunakan endpoint PUT /payroll/periods/:id/confirm-attendance.');
    }

    // Get run number
    const lastRunNumber = await payrollRepository.findLatestRunNumber(data.companyId);
    const runNumber = lastRunNumber + 1;

    // Create run
    const run = await payrollRepository.createPayrollRun(data, runNumber);

    // Run payroll calculation
    await this.calculatePayroll(run.id);

    // Publish event
    await eventBus.publish({
      name: DomainEvents.PAYROLL_RUN_CREATED,
      aggregateId: run.id,
      aggregateType: 'PayrollRun',
      data: { runNumber, companyId: data.companyId, periodId: data.periodId },
      metadata: {
        eventId: uuidv4(),
        occurredAt: new Date(),
      },
    });

    logger.info('Payroll run created', { runId: run.id, runNumber });
    return this.findPayrollRunById(run.id);
  }

  async approvePayrollRun(id: string, userId: string) {
    const run = await this.findPayrollRunById(id);
    if (run.status !== 'COMPLETED') {
      throw new BadRequestError('Only completed payroll runs can be approved');
    }

    const approved = await payrollRepository.updatePayrollRunStatus(id, 'APPROVED', userId);

    await eventBus.publish({
      name: DomainEvents.PAYROLL_RUN_APPROVED,
      aggregateId: id,
      aggregateType: 'PayrollRun',
      data: { approvedBy: userId },
      metadata: {
        eventId: uuidv4(),
        occurredAt: new Date(),
      },
    });

    return approved;
  }

  async disbursePayrollRun(id: string, userId: string) {
    const run = await this.findPayrollRunById(id);
    if (run.status !== 'APPROVED') {
      throw new BadRequestError('Only approved payroll runs can be disbursed');
    }

    const employeeIds = Array.from(new Set((run.payslips || []).map((payslip) => payslip.employeeId)));
    await employeeLoanRepository.applyPayrollDeductions(
      run.companyId,
      employeeIds,
      new Date(run.period.endDate),
      new Date(),
      run.runNumber
    );

    const disbursed = await payrollRepository.updatePayrollRunStatus(id, 'DISBURSED', userId);

    await eventBus.publish({
      name: DomainEvents.PAYROLL_RUN_DISBURSED,
      aggregateId: id,
      aggregateType: 'PayrollRun',
      data: { disbursedBy: userId },
      metadata: {
        eventId: uuidv4(),
        occurredAt: new Date(),
      },
    });

    return disbursed;
  }

  // ==================== B.6 Multibank Disbursement (CSV Export ====================

  /**
   * Group payslips per bank + generate CSV bulk transfer untuk BCA/Mandiri/BNI.
   * Prioritas bank: EmployeeBankAccount primary → first active → legacy bank fields.
   */
  async getPayrollRunDisbursements(runId: string, bankCodeFilter?: string) {
    const run = await this.findPayrollRunById(runId);
    const employeesMap: Record<string, EmployeeForDisbursement> = {};
    for (const ps of (run.payslips ?? [])) {
      const e = (ps as any).employee as any;
      if (e) employeesMap[e.id] = e as EmployeeForDisbursement;
    }
    const groups = groupPayslipsByBank((run.payslips ?? []) as any, employeesMap);
    let filtered = groups;
    if (bankCodeFilter) {
      const bc = bankCodeFilter.toUpperCase();
      filtered = groups.filter((g: any) => g.bankCode === bc);
    }
    const groupsWithCsv = filtered.map((group: any) => {
      const csv = generateBankCsv(group.bankCode, group.rows, group.bankName);
      // attach bank group bankName override jika OTHER
      return {
        ...group,
        csv: {
          headers: csv.headers,
          delimiter: csv.delimiter,
          filename: csv.filename,
          content: csv.content,
          totalRows: csv.totalRows,
        },
      };
    });
    // Warn for each row employee data source (per group (for audit):
    const warnings: string[] = [];
    for (const g of groupsWithCsv) {
      for (const row of g.rows) {
        const emp = employeesMap[row.employeeId];
        const info = resolveEmployeeBankInfo(emp ?? { id: row.employeeId, fullName: row.employeeName });
        if (info.warning) warnings.push(`[${row.employeeName}] ${info.warning}`);
      }
    }
    return {
      runId: run.id,
      runName: run.name,
      periodStart: run.period.startDate,
      periodEnd: run.period.endDate,
      groups: groupsWithCsv,
      totalGroups: groupsWithCsv.length,
      totalEmployees: (run.payslips ?? []).length,
      warnings,
    };
  }

  // ==================== Payslips ====================

  async findPayslipById(id: string) {
    const payslip = await payrollRepository.findPayslipById(id);
    if (!payslip) throw new NotFoundError('Payslip not found');
    // B.5 Enrich: inject grouped breakdown (earnings/deductions + statutory summary)
    const breakdown = buildPayslipBreakdown({
      baseSalary: Number(payslip.baseSalary) || 0,
      totalEarnings: Number(payslip.totalEarnings) || 0,
      totalDeductions: Number(payslip.totalDeductions) || 0,
      netPay: Number(payslip.netPay) || 0,
      components: (payslip.components ?? []).map((c: any) => ({
        id: c.id,
        name: c.name,
        type: c.type,
        amount: Number(c.amount) || 0,
        isTaxable: c.isTaxable,
        salaryComponent: c.salaryComponent
          ? { code: (c.salaryComponent as any)?.code ?? null }
          : null,
      })),
    });
    return { ...(payslip as any), breakdown };
  }

  async findPayslipsByEmployee(employeeId: string) {
    return payrollRepository.findPayslipsByEmployee(employeeId);
  }

  // ==================== Payroll Calculation ====================

  private async calculatePayroll(runId: string) {
    const run = await payrollRepository.findPayrollRunById(runId);
    if (!run) throw new NotFoundError('Payroll run not found');

    // Get all employees with active salary in this company
    const employeeSalaries = await payrollRepository.findAllEmployeeSalaries(run.companyId);
    const loanDeductionComponent = await this.ensureLoanDeductionComponent(run.companyId);
    const overtimeEarningComponent = await this.ensureOvertimeEarningComponent(run.companyId);
    const lateDeductionComponent = await this.ensureLateDeductionComponent(run.companyId);
    const absenceDeductionComponent = await this.ensureAbsenceDeductionComponent(run.companyId);
    const ewaDeductionComponent = await this.ensureEWADeductionComponent(run.companyId);
    const lateCfg = await companySettingsService.getLateDeductionConfig(run.companyId);
    const dueLoanInstallments = await employeeLoanRepository.findDueInstallmentsForPayroll(
      run.companyId,
      new Date(run.period.endDate)
    );
    const loanDeductionByEmployee = dueLoanInstallments.reduce<Record<string, number>>((acc, installment) => {
      const employeeId = installment.loan.employeeId;
      acc[employeeId] = (acc[employeeId] || 0) + Number(installment.amount);
      return acc;
    }, {});

    // Aggregate approved overtime hours per employee within the pay period
    const approvedOvertimes = await prisma.overtimeRequest.findMany({
      where: {
        companyId: run.companyId,
        status: 'APPROVED',
        date: { gte: new Date(run.period.startDate), lte: new Date(run.period.endDate) },
        deletedAt: null,
      },
      select: { employeeId: true, durationHours: true },
    });
    const overtimeHoursByEmployee = approvedOvertimes.reduce<Record<string, number>>((acc, ot) => {
      acc[ot.employeeId] = (acc[ot.employeeId] || 0) + Number(ot.durationHours);
      return acc;
    }, {});

    const periodStart = new Date(run.period.startDate);
    const periodEnd = new Date(run.period.endDate);

    // EWA: Fetch semua PAID status EWA yang belum di-deduct (payrollRunId null) untuk periode ini
    const paidEWAsForPeriod = await ewaRepository.findPAIDByEmployeeAndPeriod(
      run.companyId,
      'all',
      periodStart,
      periodEnd,
    ) as any[];
    const ewaAggregated = ewaService.aggregateDeductionsForPayroll(paidEWAsForPeriod);
    const ewaDeductionByEmployee: Record<string, { total: number; ewaIds: string[]; amountMap: Record<string, number> }> = {};
    for (const row of ewaAggregated as any[]) {
      if (!ewaDeductionByEmployee[row.employeeId]) {
        ewaDeductionByEmployee[row.employeeId] = { total: 0, ewaIds: [], amountMap: {} };
      }
      const amount = Number(row.deductedAmount ?? row.amountPaidOut ?? row.amountRequested ?? 0);
      ewaDeductionByEmployee[row.employeeId].total += amount;
      if (row.id) {
        ewaDeductionByEmployee[row.employeeId].ewaIds.push(row.id);
        ewaDeductionByEmployee[row.employeeId].amountMap[row.id] = amount;
      }
    }

    // Batch attendance summary per employee for the pay period
    const attendanceGroups = await prisma.attendance.groupBy({
      by: ['employeeId', 'status'],
      where: { companyId: run.companyId, date: { gte: periodStart, lte: periodEnd }, deletedAt: null },
      _count: { id: true },
    });
    const attendanceByEmployee: Record<string, { present: number; absent: number }> = {};
    for (const row of attendanceGroups) {
      if (!attendanceByEmployee[row.employeeId]) attendanceByEmployee[row.employeeId] = { present: 0, absent: 0 };
      if (row.status === 'PRESENT' || row.status === 'LATE') attendanceByEmployee[row.employeeId].present += row._count.id;
      else if (row.status === 'ABSENT') attendanceByEmployee[row.employeeId].absent += row._count.id;
    }

    // Batch approved leave days per employee overlapping the pay period
    const approvedLeaves = await prisma.leaveRequest.findMany({
      where: {
        companyId: run.companyId,
        status: 'APPROVED',
        deletedAt: null,
        OR: [
          { startDate: { gte: periodStart, lte: periodEnd } },
          { endDate: { gte: periodStart, lte: periodEnd } },
          { startDate: { lte: periodStart }, endDate: { gte: periodEnd } },
        ],
      },
      select: { employeeId: true, totalDays: true },
    });
    const leaveByEmployee = approvedLeaves.reduce<Record<string, number>>((acc, lr) => {
      acc[lr.employeeId] = (acc[lr.employeeId] || 0) + lr.totalDays;
      return acc;
    }, {});

    // Working days in period from company-level calendar (shared across all employees)
    const companyCalendar = await workCalendarRepository.findCalendarByContext({ companyId: run.companyId });
    const workDaysInPeriod = companyCalendar
      ? await workCalendarRepository.countWorkingDays(companyCalendar.id, periodStart, periodEnd)
      : 0;

    // Task 4.2 — Aggregate net LATE MINUTES per employee + per day key for daily cap deduction
    // Late minutes reduced by BranchAttendancePolicy.lateToleranceMinutes per attendance row
    const netLateMinutesByEmployee: Record<string, number> = {};
    const perDayLateMinutesByEmployee: Record<string, Record<string, number>> = {};
    if (lateCfg.enabled) {
      const lateAttendanceRows = await prisma.attendance.findMany({
        where: {
          companyId: run.companyId,
          date: { gte: periodStart, lte: periodEnd },
          deletedAt: null,
          lateMinutes: { gt: 0 },
          OR: [{ status: 'LATE' }, { status: 'PRESENT' }],
        },
        select: {
          employeeId: true,
          date: true,
          lateMinutes: true,
          attendancePolicy: { select: { lateToleranceMinutes: true } },
        },
      });
      for (const row of lateAttendanceRows) {
        const tolerance = Number(row.attendancePolicy?.lateToleranceMinutes ?? 0);
        const netMinutes = Math.max(0, Number(row.lateMinutes ?? 0) - tolerance);
        if (netMinutes <= 0) continue;
        netLateMinutesByEmployee[row.employeeId] = (netLateMinutesByEmployee[row.employeeId] || 0) + netMinutes;
        const dayKey = new Date(row.date).toISOString().slice(0, 10);
        if (!perDayLateMinutesByEmployee[row.employeeId]) perDayLateMinutesByEmployee[row.employeeId] = {};
        perDayLateMinutesByEmployee[row.employeeId][dayKey] = (perDayLateMinutesByEmployee[row.employeeId][dayKey] || 0) + netMinutes;
      }
    }

    // Delete existing payslips for this run (recalculation)
    await payrollRepository.deletePayslipsByRunId(runId);

    let totalEarnings = 0;
    let totalDeductions = 0;
    let employeeCount = 0;

    for (const salary of employeeSalaries) {
      if (!salary.isActive) continue;

      const loanDeductionAmount = loanDeductionByEmployee[salary.employeeId] || 0;
      const overtimeHoursForEmployee = overtimeHoursByEmployee[salary.employeeId] || 0;
      const attd = attendanceByEmployee[salary.employeeId] ?? { present: 0, absent: 0 };
      const leaveDaysForEmployee = leaveByEmployee[salary.employeeId] ?? 0;
      const absentDays = Math.max(0, workDaysInPeriod - attd.present - leaveDaysForEmployee);
      const overtimePayAmount = overtimeHoursForEmployee > 0
        ? calculateOvertimePay({ monthlyWage: Number(salary.baseSalary), hours: overtimeHoursForEmployee, dayType: 'WORKDAY' }).amount
        : 0;

      // Task 4.2 — Hitung nominal potongan keterlambatan (dengan daily cap persentase gaji pokok)
      const baseMonthlyWage = Number(salary.baseSalary);
      let lateDeductionAmount = 0;
      if (lateCfg.enabled && perDayLateMinutesByEmployee[salary.employeeId]) {
        const dailyCapIdr = baseMonthlyWage * (lateCfg.dailyCapPercentOfBasic / 100);
        const dayMap = perDayLateMinutesByEmployee[salary.employeeId];
        for (const dayKey in dayMap) {
          const dayRawAmount = dayMap[dayKey] * lateCfg.ratePerMinuteIdr;
          lateDeductionAmount += Math.min(dayRawAmount, dailyCapIdr);
        }
        lateDeductionAmount = Math.round(lateDeductionAmount);
      }
      // Task 4.2 — Hitung nominal potongan alpha tidak hadir (persen × gaji / hari kerja default)
      let absenceDeductionAmount = 0;
      if (absentDays > 0 && lateCfg.absenceDailyPercentOfBasic > 0 && lateCfg.defaultWorkingDaysPerMonth > 0) {
        const perDayWageRate = baseMonthlyWage / lateCfg.defaultWorkingDaysPerMonth;
        const perDayDeduction = perDayWageRate * (lateCfg.absenceDailyPercentOfBasic / 100);
        absenceDeductionAmount = Math.round(perDayDeduction * absentDays);
      }

      const extraComponents: Array<{ salaryComponentId: string; name: string; type: string; amount: number; isTaxable: boolean }> = [];
      if (loanDeductionAmount > 0) {
        extraComponents.push({
          salaryComponentId: loanDeductionComponent.id,
          name: 'Potongan Pinjaman Karyawan',
          type: 'DEDUCTION',
          amount: loanDeductionAmount,
          isTaxable: false,
        });
      }
      if (overtimePayAmount > 0) {
        extraComponents.push({
          salaryComponentId: overtimeEarningComponent.id,
          name: 'Tunjangan Lembur',
          type: 'ALLOWANCE',
          amount: overtimePayAmount,
          isTaxable: true,
        });
      }
      if (lateDeductionAmount > 0) {
        extraComponents.push({
          salaryComponentId: lateDeductionComponent.id,
          name: 'Potongan Keterlambatan',
          type: 'DEDUCTION',
          amount: lateDeductionAmount,
          isTaxable: false,
        });
      }
      if (absenceDeductionAmount > 0) {
        extraComponents.push({
          salaryComponentId: absenceDeductionComponent.id,
          name: 'Potongan Tidak Hadir (Alpha)',
          type: 'DEDUCTION',
          amount: absenceDeductionAmount,
          isTaxable: false,
        });
      }
      const ewaDeductInfo = ewaDeductionByEmployee[salary.employeeId];
      const ewaDeductionAmount = ewaDeductInfo?.total || 0;
      if (ewaDeductionAmount > 0) {
        extraComponents.push({
          salaryComponentId: ewaDeductionComponent.id,
          name: 'Potongan EWA (Tarik Gaji Awal)',
          type: 'DEDUCTION',
          amount: ewaDeductionAmount,
          isTaxable: false,
        });
      }

      const emp = salary.employee as { maritalStatus?: string | null; taxId?: string | null; _count?: { families: number } };
      const taxContext = {
        married: emp?.maritalStatus === 'MARRIED',
        dependents: emp?._count?.families ?? 0,
        hasNpwp: Boolean(emp?.taxId),
      };

      const { earningsTotal, deductionsTotal, components } = this.calculateEmployeePay(salary, extraComponents, taxContext);
      const netPay = earningsTotal - deductionsTotal;

      // Create payslip
      const payslip = await payrollRepository.createPayslip({
        payrollRun: { connect: { id: runId } },
        employee: { connect: { id: salary.employeeId } },
        company: { connect: { id: run.companyId } },
        employeeSalary: { connect: { id: salary.id } },
        baseSalary: salary.baseSalary,
        totalEarnings: earningsTotal,
        totalDeductions: deductionsTotal,
        netPay,
        workDays: workDaysInPeriod,
        presentDays: attd.present,
        leaveDays: leaveDaysForEmployee,
        absentDays,
        overtimeHours: overtimeHoursForEmployee,
        status: 'DRAFT',
      });

      // Create payslip components
      if (components.length > 0) {
        await payrollRepository.createPayslipComponents(
          components.map((c) => ({
            payslipId: payslip.id,
            salaryComponentId: c.salaryComponentId,
            name: c.name,
            type: c.type as any,
            amount: c.amount,
            isTaxable: c.isTaxable,
          }))
        );
      }

      totalEarnings += earningsTotal;
      totalDeductions += deductionsTotal;
      employeeCount++;
    }

    // EWA: Bulk mark semua PAID EWA yang sudah di-deduct di payroll run ini menjadi DEDUCTED + attach payrollRunId supaya recalculate tidak double deduct
    const allEwaIds: string[] = [];
    const ewaAmountMapGlobal: Record<string, number> = {};
    for (const emp of Object.values(ewaDeductionByEmployee)) {
      allEwaIds.push(...emp.ewaIds);
      Object.assign(ewaAmountMapGlobal, emp.amountMap);
    }
    if (allEwaIds.length > 0) {
      await ewaRepository.bulkMarkDeducted(allEwaIds, runId, new Date(), ewaAmountMapGlobal);
    }

    // Update run totals
    await payrollRepository.updatePayrollRunTotals(runId, {
      totalEmployees: employeeCount,
      totalEarnings,
      totalDeductions,
      totalNetPay: totalEarnings - totalDeductions,
    });

    // Mark run as completed
    await payrollRepository.updatePayrollRunStatus(runId, 'COMPLETED');

    logger.info('Payroll calculation completed', {
      runId,
      employeeCount,
      totalEarnings,
      totalDeductions,
    });
  }

  private async ensureOvertimeEarningComponent(companyId: string) {
    const code = 'OVERTIME_EARNING_AUTO';
    const existing = await payrollRepository.findSalaryComponentByCode(companyId, code);
    if (existing) return existing;
    return payrollRepository.createSalaryComponent({
      companyId,
      name: 'Tunjangan Lembur',
      code,
      type: 'ALLOWANCE',
      calculationMethod: 'FIXED',
      amount: 0,
      isTaxable: true,
      isProrated: false,
      description: 'System generated: overtime pay per PP 35/2021',
      sortOrder: 998,
    });
  }

  private async ensureLoanDeductionComponent(companyId: string) {
    const code = 'LOAN_DEDUCTION_AUTO';
    const existing = await payrollRepository.findSalaryComponentByCode(companyId, code);

    if (existing) {
      return existing;
    }

    return payrollRepository.createSalaryComponent({
      companyId,
      name: 'Potongan Pinjaman Karyawan',
      code,
      type: 'DEDUCTION',
      calculationMethod: 'FIXED',
      amount: 0,
      isTaxable: false,
      isProrated: false,
      description: 'System generated deduction for employee loan installments',
      sortOrder: 999,
    });
  }

  private async ensureLateDeductionComponent(companyId: string) {
    const code = 'LATE_DEDUCTION_AUTO';
    const existing = await payrollRepository.findSalaryComponentByCode(companyId, code);
    if (existing) return existing;
    return payrollRepository.createSalaryComponent({
      companyId,
      name: 'Potongan Keterlambatan',
      code,
      type: 'DEDUCTION',
      calculationMethod: 'FIXED',
      amount: 0,
      isTaxable: false,
      isProrated: false,
      description: 'System generated: automatic late attendance deduction per minutes after branch tolerance',
      sortOrder: 997,
    });
  }

  private async ensureAbsenceDeductionComponent(companyId: string) {
    const code = 'ABSENCE_DEDUCTION_AUTO';
    const existing = await payrollRepository.findSalaryComponentByCode(companyId, code);
    if (existing) return existing;
    return payrollRepository.createSalaryComponent({
      companyId,
      name: 'Potongan Tidak Hadir (Alpha)',
      code,
      type: 'DEDUCTION',
      calculationMethod: 'FIXED',
      amount: 0,
      isTaxable: false,
      isProrated: false,
      description: 'System generated: automatic absence per day deduction based on basic salary / working days',
      sortOrder: 996,
    });
  }

  private async ensureEWADeductionComponent(companyId: string) {
    const code = 'EWA-DEDUCT';
    const existing = await payrollRepository.findSalaryComponentByCode(companyId, code);
    if (existing) return existing;
    return payrollRepository.createSalaryComponent({
      companyId,
      name: 'Potongan EWA (Tarik Gaji Awal)',
      code,
      type: 'DEDUCTION',
      calculationMethod: 'FIXED',
      amount: 0,
      isTaxable: false,
      isProrated: false,
      description: 'System generated: automatic deduction for approved Earned Wage Access paid requests (employer-funded float model). Deducted bulan berjalan di payslip.',
      sortOrder: 995,
    });
  }

  private calculateEmployeePay(
    salary: any,
    extraComponents: Array<{
      salaryComponentId: string;
      name: string;
      type: string;
      amount: number;
      isTaxable: boolean;
    }> = [],
    taxContext?: { married: boolean; dependents: number; hasNpwp: boolean }
  ) {
    const wage = Number(salary.baseSalary);

    // Pass 1: resolve each active component's amount (percentage on base wage).
    const resolved = (salary.components as any[])
      .filter((c) => c.isActive)
      .map((comp) => {
        const sc = comp.salaryComponent;
        let amount = Number(comp.amount);
        if (sc.calculationMethod === 'PERCENTAGE' && sc.ratePercent) {
          amount = wage * (Number(sc.ratePercent) / 100);
        } else if (sc.calculationMethod === 'FORMULA') {
          // ponytail: FORMULA is declared in schema but not yet implemented; throw so it doesn't silently return zero
          throw new Error(`Salary component "${sc.name}" uses FORMULA calculationMethod which is not yet supported`);
        }
        return {
          code: sc.code as string,
          entry: {
            salaryComponentId: sc.id,
            name: sc.name,
            type: sc.type as any,
            amount,
            isTaxable: sc.isTaxable,
          },
        };
      });

    // Task 2.6/2.7: statutory engines replace the naive flat-rate components.
    const taxableGross = resolved
      .filter((r) => r.entry.type === 'ALLOWANCE' && r.entry.isTaxable)
      .reduce((sum, r) => sum + r.entry.amount, 0);
    const bpjs = calculateBpjs(wage);
    const pension = bpjs.employee.jht + bpjs.employee.jp; // deductible from PPh21 gross
    const pph = taxContext
      ? calculatePph21({
          monthlyGross: taxableGross,
          married: taxContext.married,
          dependents: taxContext.dependents,
          monthlyPensionContribution: pension,
          hasNpwp: taxContext.hasNpwp,
        })
      : null;

    for (const r of resolved) {
      if (r.code === 'BPJS-TK') r.entry.amount = bpjs.employee.jht + bpjs.employee.jp;
      else if (r.code === 'BPJS-KES') r.entry.amount = bpjs.employee.jkn;
      else if (r.code === 'PPH21' && pph) r.entry.amount = pph.monthlyTax;
    }

    let earningsTotal = 0;
    let deductionsTotal = 0;
    const components = resolved.map((r) => r.entry);
    for (const r of resolved) {
      if (r.entry.type === 'ALLOWANCE') earningsTotal += r.entry.amount;
      else deductionsTotal += r.entry.amount;
    }

    for (const comp of extraComponents) {
      components.push(comp);
      if (comp.type === 'ALLOWANCE') earningsTotal += comp.amount;
      else deductionsTotal += comp.amount;
    }

    return { earningsTotal, deductionsTotal, components };
  }

  // ==================== Standalone Calculation Endpoints (B.1, B.2, B.3) ====================

  calculatePph21Standalone(data: CalculatePph21DTO) {
    return calculatePph21({
      monthlyGross: data.monthlyGross,
      married: data.married,
      dependents: data.dependents,
      monthlyPensionContribution: data.monthlyPensionContribution,
      hasNpwp: data.hasNpwp,
    });
  }

  calculateThrStandalone(data: CalculateThrStandaloneDTO) {
    const result = calculateThr({
      monthlyWage: data.monthlyWage,
      joinDate: new Date(data.joinDate),
      referenceDate: data.referenceDate ? new Date(data.referenceDate) : new Date(),
    });
    // BONUS: hitung also PPh 21 untuk THR (aturan khusus THR: PPh dihitung tersendiri nanti)
    // Saat ini return amount THR saja sesuai acceptance B.2.
    return {
      ...result,
      monthlyWage: data.monthlyWage,
      joinDate: data.joinDate,
    };
  }

  calculateBpjsStandalone(data: CalculateBpjsDTO) {
    const baseRiskRate = JKK_RISK_TO_RATE[data.jkkRiskClass as JKKRiskClass];
    const mergedConfig = {
      jkkRatePercent: baseRiskRate,
      ...(data.customRates ?? {}),
    };
    const breakdown = calculateBpjs(data.monthlyWage, mergedConfig);
    return {
      jkkRiskClass: data.jkkRiskClass,
      configApplied: mergedConfig,
      ...breakdown,
    };
  }

  calculateJknStandalone(data: CalculateJknDTO) {
    const breakdown = calculateBpjs(data.monthlyWage, data.customRates ?? {});
    const base = Math.min(Math.max(0, data.monthlyWage), data.customRates?.jknWageCap ?? 12_000_000);
    return {
      monthlyWage: data.monthlyWage,
      jknBaseWage: base,
      configApplied: {
        jknEmployerPercent: data.customRates?.jknEmployerPercent ?? 4,
        jknEmployeePercent: data.customRates?.jknEmployeePercent ?? 1,
        jknWageCap: data.customRates?.jknWageCap ?? 12_000_000,
      },
      employee: { jkn: breakdown.employee.jkn },
      employer: { jkn: breakdown.employer.jkn },
      totalPerPerson: breakdown.employee.jkn + breakdown.employer.jkn,
    };
  }
}

export const payrollService = new PayrollService();
