import { payrollRepository } from './payroll.repository';
import {
  CreateSalaryComponentDTO,
  UpdateSalaryComponentDTO,
  CreateEmployeeSalaryDTO,
  UpdateEmployeeSalaryDTO,
  CreatePayrollPeriodDTO,
  UpdatePayrollPeriodDTO,
  CreatePayrollRunDTO,
  CalculatePph21DTO,
  CalculateThrStandaloneDTO,
  CalculateBpjsDTO,
  CalculateJknDTO,
} from './payroll.dto';
import { eventBus } from '@/shared/events/EventBus';
import { DomainEvents } from '@/shared/events/events';
import { logger } from '@/shared/logger/WinstonLogger';
import { NotFoundError, ConflictError, BadRequestError, ValidationError, ForbiddenError } from '@/shared/exceptions/AppError';
import { randomUUID as uuidv4 } from 'node:crypto';
import { employeeLoanRepository } from '@/modules/employee-loan/employee-loan.repository';
import { generateSystemCode } from '@/shared/utils/system-code';
import { calculateBpjs } from '@/shared/payroll/bpjs';
import { calculatePph21 } from '@/shared/payroll/pph21';
import { calculateThr } from '@/shared/payroll/thr';
import { buildPayslipBreakdown } from '@/shared/payroll/payslip-breakdown';
import { prisma } from '@/shared/database/prisma';
import { calculateOvertimePay } from '@/shared/attendance/overtime';
import { loadPayrollAttendance, PayrollAttendanceSummary } from './payroll-attendance';
import { payrollDate, payrollDateKey } from '@/shared/payroll/attendance-calendar';
import { companySettingsService } from '@/modules/company-settings/company-settings.service';
import { JKKRiskClass, Prisma } from '@prisma/client';
import { selectFormulaVersions } from '@/shared/payroll/formula';
import { calculateEmployeePay, PayComponent } from '@/shared/payroll/employee-pay';
import { ewaRepository, PayrollEWADeduction } from '@/modules/ewa/ewa.repository';
import { employeeSalaryService } from './employee-salary.service';
import { companyPayrollAccess, payrollAccess } from './payroll-access';

const JKK_RISK_TO_RATE: Record<JKKRiskClass, number> = {
  [JKKRiskClass.I]: 0.24,
  [JKKRiskClass.II]: 0.54,
  [JKKRiskClass.III]: 0.89,
  [JKKRiskClass.IV]: 1.27,
  [JKKRiskClass.V]: 1.74,
};

export class PayrollService {
  // ==================== Salary Components ====================

  async findAllSalaryComponents(companyId: string) {
    return payrollRepository.findAllSalaryComponents(companyId);
  }

  async findSalaryComponentById(id: string) {
    const component = await payrollRepository.findSalaryComponentById(id);
    if (!component) throw new NotFoundError('Salary component not found');
    return component;
  }

  async createSalaryComponent(data: CreateSalaryComponentDTO) {
    if (data.calculationMethod === 'FORMULA') {
      throw new BadRequestError(
        'Buat komponen FIXED atau PERCENTAGE terlebih dahulu, lalu simulasikan dan publikasikan versi formula melalui menu Formula. Metode dasar tetap berlaku sebelum tanggal efektif formula.',
      );
    }
    const code = await generateSystemCode({
      prefix: 'PAY-CMP',
      label: data.name,
      exists: async (candidate) => Boolean(await payrollRepository.findSalaryComponentByCode(data.companyId, candidate)),
    });
    const existing = await payrollRepository.findSalaryComponentByCode(data.companyId, code);
    if (existing) throw new ConflictError('Salary component code already exists');

    const component = await payrollRepository.createSalaryComponent({ ...data, code });

    logger.info('Salary component created', { componentId: component.id, code: component.code });
    return component;
  }

  async updateSalaryComponent(id: string, data: UpdateSalaryComponentDTO) {
    const currentComponent = await this.findSalaryComponentById(id);
    if (data.calculationMethod === 'FORMULA') {
      throw new BadRequestError(
        'Buat komponen FIXED atau PERCENTAGE terlebih dahulu, lalu simulasikan dan publikasikan versi formula melalui menu Formula. Metode dasar tetap berlaku sebelum tanggal efektif formula.',
      );
    }
    const requestedCode = (data as Record<string, unknown>).code;
    if (typeof requestedCode === 'string' && requestedCode !== currentComponent.code) {
      throw new ValidationError('Salary component code is generated by system and cannot be changed');
    }
    const component = await payrollRepository.updateSalaryComponent(id, data);

    logger.info('Salary component updated', { componentId: id });
    return component;
  }

  async deleteSalaryComponent(id: string) {
    await this.findSalaryComponentById(id);
    await payrollRepository.softDeleteSalaryComponent(id);

    logger.info('Salary component deleted', { componentId: id });
  }

  // ==================== Employee Salaries ====================

  async findAllEmployeeSalaries(companyId: string, employeeId?: string) {
    return employeeSalaryService.list(companyId, employeeId);
  }

  async findEmployeeSalaryById(id: string) {
    return employeeSalaryService.findById(id);
  }

  async createEmployeeSalary(data: CreateEmployeeSalaryDTO) {
    const salary = await employeeSalaryService.create(data);

    logger.info('Employee salary created', {
      employeeId: data.employeeId,
      salaryId: salary.id,
    });

    return salary;
  }

  async updateEmployeeSalary(id: string, data: UpdateEmployeeSalaryDTO) {
    return employeeSalaryService.update(id, data);
  }

  /**
   * Hitung THR seorang karyawan (Business Rule Gap: Permenaker 6/2016).
   * ≥12 bulan = 1× upah; 1–<12 bulan = prorata (masa kerja/12 × upah); <1 bulan = tidak berhak.
   */
  async calculateEmployeeThr(employeeId: string, referenceDate?: Date) {
    if (referenceDate && !Number.isFinite(referenceDate.getTime())) throw new ValidationError('Invalid THR reference date');
    const { salary, employee } = await employeeSalaryService.thrInputs(employeeId);
    if (!employee) throw new NotFoundError('Employee not found');
    if (!employee.joinDate) {
      throw new BadRequestError('Tanggal masuk (joinDate) karyawan belum diisi');
    }
    if (!salary) {
      throw new BadRequestError('Data gaji aktif karyawan tidak ditemukan');
    }

    const result = calculateThr({
      monthlyWage: Number(salary.baseSalary),
      joinDate: employee.joinDate,
      referenceDate: referenceDate ?? new Date(),
    });

    logger.info('THR calculated', { employeeId });

    return {
      employee: { id: employee.id, fullName: employee.fullName, employeeNumber: employee.employeeNumber },
      monthlyWage: Number(salary.baseSalary),
      ...result,
    };
  }

  // ==================== Payroll Periods ====================

  async findAllPayrollPeriods(companyId: string) {
    const access = await companyPayrollAccess(companyId);
    return payrollRepository.findAllPayrollPeriods(access.companyId);
  }

  async findPayrollPeriodById(id: string) {
    const { companyId } = await companyPayrollAccess();
    const period = await payrollRepository.findPayrollPeriodById(id, prisma, companyId);
    if (!period) throw new NotFoundError('Payroll period not found');
    return period;
  }

  async createPayrollPeriod(data: CreatePayrollPeriodDTO) {
    const { companyId } = await companyPayrollAccess(data.companyId);
    data = { ...data, companyId };
    const code = await generateSystemCode({
      prefix: 'PAY-PRD',
      label: data.name,
      exists: async (candidate) => {
        const periods = await payrollRepository.findAllPayrollPeriods(data.companyId);
        return periods.some((period) => period.code === candidate);
      },
    });
    const period = await payrollRepository.createPayrollPeriod({ ...data, code });

    logger.info('Payroll period created', { periodId: period.id, code: period.code });
    return period;
  }

  async closePayrollPeriod(id: string) {
    const existing = await this.findPayrollPeriodById(id);
    const period = await payrollRepository.closePayrollPeriod(id, existing.companyId);

    logger.info('Payroll period closed', { periodId: id });
    return period;
  }

  async updatePayrollPeriod(id: string, data: UpdatePayrollPeriodDTO) {
    const period = await this.findPayrollPeriodById(id);
    const requestedCode = (data as Record<string, unknown>).code;
    if (typeof requestedCode === 'string' && requestedCode !== period.code) {
      throw new ValidationError('Payroll period code is generated by system and cannot be changed');
    }
    if (period.status === 'CLOSED') {
      throw new BadRequestError('Cannot update a closed payroll period');
    }
    return payrollRepository.updatePayrollPeriod(id, data, period.companyId);
  }

  // ==================== Payroll Runs ====================

  async findAllPayrollRuns(companyId: string) {
    const access = await companyPayrollAccess(companyId);
    return payrollRepository.findAllPayrollRuns(access.companyId);
  }

  async findPayrollRunById(id: string) {
    const { companyId } = await companyPayrollAccess();
    const run = await payrollRepository.findPayrollRunForAccess(id, companyId);
    if (!run) throw new NotFoundError('Payroll run not found');
    return run;
  }

  async getAttendanceSummaryForPeriod(periodId: string) {
    const { companyId } = await companyPayrollAccess();
    return prisma.$transaction(async database => {
      const period = await payrollRepository.findPayrollPeriodById(periodId, database, companyId);
      if (!period) throw new NotFoundError('Payroll period not found');
      const salaries = await payrollRepository.findAllEmployeeSalaries(period.companyId, undefined, database);
      const inputs = await loadPayrollAttendance(database, period.companyId,
        salaries.filter(salary => salary.isActive).map(salary => salary.employeeId), period.startDate, period.endDate);
      const summary: Record<string, PayrollAttendanceSummary> = {};
      for (const [employeeId, row] of inputs) {
        summary[employeeId] = { workDays: row.workDays, present: row.present, absent: row.absent, leave: row.leave, overtime: row.overtime };
      }
      return { period, attendanceReviewedAt: period.attendanceReviewedAt, summary };
    }, { isolationLevel: Prisma.TransactionIsolationLevel.RepeatableRead, maxWait: 10000, timeout: 60000 });
  }

  async confirmAttendanceReview(periodId: string, userId: string) {
    const { companyId, actor } = await companyPayrollAccess(undefined, userId);
    const period = await this.findPayrollPeriodById(periodId);
    if (period.status === 'CLOSED') throw new BadRequestError('Period sudah ditutup');
    return payrollRepository.confirmAttendanceReview(periodId, actor.id, companyId);
  }

  async createPayrollRun(data: CreatePayrollRunDTO, userId?: string) {
    if (!userId) throw new BadRequestError('Authenticated payroll creator is required');
    const { companyId, actor } = await companyPayrollAccess(data.companyId, userId);
    data = { ...data, companyId };
    const run = await this.createPayrollRunTransaction(data, actor.id);
    // No external side effects run until the payroll transaction has committed.
    try {
      await eventBus.publish({
        name: DomainEvents.PAYROLL_RUN_CREATED,
        aggregateId: run.id,
        aggregateType: 'PayrollRun',
        data: { runNumber: run.runNumber, companyId: data.companyId, periodId: data.periodId },
        metadata: { eventId: uuidv4(), occurredAt: new Date() },
      });
    } catch {
      logger.warn('Payroll event publication failed after commit', { runId: run.id });
    }
    logger.info('Payroll run created', { runId: run.id, runNumber: run.runNumber });
    return this.findPayrollRunById(run.id);
  }

  private async createPayrollRunTransaction(data: CreatePayrollRunDTO, userId: string) {
    for (let attempt = 0; ; attempt++) {
      try {
        return await prisma.$transaction(async tx => {
          // Same lock as formula publication: revisions cannot change midway
          // through a run, and requests for this company receive distinct numbers.
          const company = await tx.$queryRaw<{ id: string }[]>`SELECT id FROM companies WHERE id = ${data.companyId} AND deleted_at IS NULL FOR UPDATE`;
          if (!company.length) throw new NotFoundError('Company not found');
          const period = await payrollRepository.findPayrollPeriodById(data.periodId, tx, data.companyId);
          if (!period || period.companyId !== data.companyId) throw new NotFoundError('Payroll period not found in this company');
          if (period.status === 'CLOSED') throw new BadRequestError('Cannot create payroll run for a closed period');
          if (!period.attendanceReviewedAt) throw new BadRequestError('Attendance harus dikonfirmasi sebelum payroll dihitung.');
          const existing = await tx.payrollRun.findFirst({ where: { companyId: data.companyId, periodId: period.id, deletedAt: null }, select: { id: true } });
          if (existing) throw new ConflictError(`Payroll already exists for this period (${existing.id}); review the existing run before creating a correction`);
          const runNumber = await payrollRepository.findLatestRunNumber(data.companyId, tx) + 1;
          const run = await payrollRepository.createPayrollRun(data, runNumber, userId, tx);
          await this.calculatePayroll(run.id, tx);
          return run;
        }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, maxWait: 10000, timeout: 60000 });
      } catch (error) {
        if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2034' && attempt < 2) continue;
        throw error;
      }
    }
  }

  async approvePayrollRun(id: string, userId: string) {
    const { companyId, actor } = await companyPayrollAccess(undefined, userId);
    const run = await this.findPayrollRunById(id);
    if (run.status !== 'COMPLETED') {
      throw new BadRequestError('Only completed payroll runs can be approved');
    }

    if (!run.createdBy) throw new ConflictError('Payroll creator is unknown; legacy payroll requires review before approval');
    if (run.createdBy === actor.id) throw new ConflictError('Payroll creator cannot approve their own run');
    const approved = await payrollRepository.approvePayrollRun(id, actor.id, companyId);

    await eventBus.publish({
      name: DomainEvents.PAYROLL_RUN_APPROVED,
      aggregateId: id,
      aggregateType: 'PayrollRun',
      data: { approvedBy: userId },
      metadata: {
        eventId: uuidv4(),
        occurredAt: new Date(),
      },
    });

    return approved;
  }

  async disbursePayrollRun(id: string, _userId: string): Promise<never> {
    await this.findPayrollRunById(id);
    throw new ConflictError('Direct disbursement is disabled. Create a payment batch, record payment results, then reconcile it.');
  }

  // ==================== B.6 Multibank Disbursement (CSV Export ====================

  /**
   * Group payslips per bank + generate CSV bulk transfer untuk BCA/Mandiri/BNI.
   * Prioritas bank: EmployeeBankAccount primary → first active → legacy bank fields.
   */
  async getPayrollRunDisbursements(runId: string, _bankCodeFilter?: string): Promise<never> {
    await this.findPayrollRunById(runId);
    throw new ConflictError('Create a payment batch and export its immutable bank file from /payroll/payment-batches/:id/export.');
  }

  // ==================== Payslips ====================

  async findPayslipById(id: string) {
    const { companyId, employeeWhere } = await payrollAccess();
    const payslip = await payrollRepository.findPayslipById(id, companyId, employeeWhere);
    if (!payslip) throw new NotFoundError('Payslip not found');
    // B.5 Enrich: inject grouped breakdown (earnings/deductions + statutory summary)
    const breakdown = buildPayslipBreakdown({
      baseSalary: Number(payslip.baseSalary) || 0,
      totalEarnings: Number(payslip.totalEarnings) || 0,
      totalDeductions: Number(payslip.totalDeductions) || 0,
      netPay: Number(payslip.netPay) || 0,
      components: (payslip.components ?? []).map(c => ({
        id: c.id,
        name: c.name,
        type: c.type,
        amount: Number(c.amount) || 0,
        isTaxable: c.isTaxable,
        salaryComponent: c.salaryComponent
          ? { code: c.salaryComponent.code }
          : null,
      })),
    });
    return { ...payslip, breakdown };
  }

  async findPayslipsByEmployee(employeeId: string) {
    const { companyId, actor, employeeWhere } = await payrollAccess();
    if (!actor.employeeId || actor.employeeId !== employeeId) throw new ForbiddenError('Self-service payslips require the authenticated employee');
    return payrollRepository.findPayslipsByEmployee(employeeId, companyId, employeeWhere);
  }

  // ==================== Payroll Calculation ====================

  private async calculatePayroll(runId: string, database: Prisma.TransactionClient) {
    const run = await payrollRepository.findPayrollRunById(runId, database);
    if (!run) throw new NotFoundError('Payroll run not found');

    // Get all employees with active salary in this company
    const employeeSalaries = await payrollRepository.findAllEmployeeSalaries(run.companyId, undefined, database);
    // Read the published revision set once for the whole run. Later publications
    // never change the version used midway through employee calculations.
    const formulaVersions = selectFormulaVersions(await database.payrollFormulaVersion.findMany({
      where: { companyId: run.companyId, status: 'PUBLISHED' },
    }), new Date(run.period.startDate));
    const loanDeductionComponent = await this.ensureLoanDeductionComponent(run.companyId, database);
    const overtimeEarningComponent = await this.ensureOvertimeEarningComponent(run.companyId, database);
    const lateDeductionComponent = await this.ensureLateDeductionComponent(run.companyId, database);
    const absenceDeductionComponent = await this.ensureAbsenceDeductionComponent(run.companyId, database);
    const ewaDeductionComponent = await this.ensureEWADeductionComponent(run.companyId, database);
    const lateCfg = await companySettingsService.getLateDeductionConfig(run.companyId, database);
    const dueLoanInstallments = await employeeLoanRepository.findDueInstallmentsForPayroll(
      run.companyId,
      new Date(run.period.endDate), database
    );
    const loanDeductionByEmployee = dueLoanInstallments.reduce<Record<string, Prisma.Decimal>>((acc, installment) => {
      const employeeId = installment.loan.employeeId;
      acc[employeeId] = (acc[employeeId] ?? new Prisma.Decimal(0)).plus(installment.amount);
      return acc;
    }, {});

    const periodStart = payrollDate(run.period.startDate);
    const periodEnd = payrollDate(run.period.endDate);
    const attendanceInputs = await loadPayrollAttendance(database, run.companyId,
      employeeSalaries.filter(salary => salary.isActive).map(salary => salary.employeeId), periodStart, periodEnd);

    const paidEWAsForPeriod = await ewaRepository.findPAIDByEmployeeAndPeriod(
      run.companyId, 'all', periodStart, periodEnd, database,
    );
    const ewaDeductionByEmployee = new Map<string, { total: Prisma.Decimal; deductions: PayrollEWADeduction[] }>();
    for (const row of paidEWAsForPeriod) {
      const amount = new Prisma.Decimal(row.amountPaidOut ?? row.amountRequested);
      if (!amount.isFinite() || amount.isNegative() || amount.greaterThan('9999999999999.99')) {
        throw new BadRequestError('EWA contains an invalid payroll deduction amount');
      }
      if (amount.isZero()) continue;
      const employee = ewaDeductionByEmployee.get(row.employeeId) ?? { total: new Prisma.Decimal(0), deductions: [] };
      employee.total = employee.total.plus(amount);
      employee.deductions.push({ id: row.id, employeeId: row.employeeId, amount,
        amountRequested: row.amountRequested, amountPaidOut: row.amountPaidOut });
      ewaDeductionByEmployee.set(row.employeeId, employee);
    }

    // Task 4.2 — Aggregate net LATE MINUTES per employee + per day key for daily cap deduction
    // Late minutes reduced by BranchAttendancePolicy.lateToleranceMinutes per attendance row
    const perDayLateMinutesByEmployee: Record<string, Record<string, number>> = {};
    if (lateCfg.enabled) {
      const lateAttendanceRows = await database.attendance.findMany({
        where: {
          companyId: run.companyId,
          date: { gte: periodStart, lte: periodEnd },
          deletedAt: null,
          lateMinutes: { gt: 0 },
          OR: [{ status: 'LATE' }, { status: 'PRESENT' }],
        },
        select: {
          employeeId: true,
          date: true,
          lateMinutes: true,
          attendancePolicy: { select: { lateToleranceMinutes: true } },
        },
      });
      for (const row of lateAttendanceRows) {
        const dayKey = payrollDateKey(row.date);
        if (!attendanceInputs.get(row.employeeId)?.workingDates.has(dayKey)) continue;
        const tolerance = Number(row.attendancePolicy?.lateToleranceMinutes ?? 0);
        const netMinutes = Math.max(0, Number(row.lateMinutes ?? 0) - tolerance);
        if (netMinutes <= 0) continue;
        if (!perDayLateMinutesByEmployee[row.employeeId]) perDayLateMinutesByEmployee[row.employeeId] = {};
        perDayLateMinutesByEmployee[row.employeeId][dayKey] = (perDayLateMinutesByEmployee[row.employeeId][dayKey] || 0) + netMinutes;
      }
    }

    let totalEarnings = new Prisma.Decimal(0);
    let totalDeductions = new Prisma.Decimal(0);
    const processedEmployees = new Set<string>();
    const appliedEwaDeductions: PayrollEWADeduction[] = [];
    let employeeCount = 0;

    for (const salary of employeeSalaries) {
      if (!salary.isActive) continue;
      if (salary.companyId !== run.companyId || salary.employee.companyId !== run.companyId || salary.components.some(allocation => allocation.salaryComponent.companyId !== run.companyId)) {
        throw new ConflictError('Salary allocation references a component outside the payroll company');
      }

      if (processedEmployees.has(salary.employeeId)) throw new ConflictError('Multiple active salaries found for one employee; review salary allocations');
      if (salary.currency !== 'IDR') throw new BadRequestError('Payroll calculation currently supports IDR salary allocations');
      processedEmployees.add(salary.employeeId);

      const loanDeductionAmount = loanDeductionByEmployee[salary.employeeId]?.toNumber() ?? 0;
      const attd = attendanceInputs.get(salary.employeeId);
      if (!attd) throw new BadRequestError('Payroll attendance inputs are unavailable for this employee');
      const workDaysInPeriod = attd.workDays;
      const overtimeHoursForEmployee = attd.overtime;
      const leaveDaysForEmployee = attd.leave;
      const absentDays = attd.absent;
      const overtimePayAmount = overtimeHoursForEmployee > 0
        ? calculateOvertimePay({ monthlyWage: Number(salary.baseSalary), hours: overtimeHoursForEmployee, dayType: 'WORKDAY' }).amount
        : 0;

      // Task 4.2 — Hitung nominal potongan keterlambatan (dengan daily cap persentase gaji pokok)
      const baseMonthlyWage = Number(salary.baseSalary);
      let lateDeductionAmount = 0;
      if (lateCfg.enabled && perDayLateMinutesByEmployee[salary.employeeId]) {
        const dailyCapIdr = baseMonthlyWage * (lateCfg.dailyCapPercentOfBasic / 100);
        const dayMap = perDayLateMinutesByEmployee[salary.employeeId];
        for (const dayKey in dayMap) {
          const dayRawAmount = dayMap[dayKey] * lateCfg.ratePerMinuteIdr;
          lateDeductionAmount += Math.min(dayRawAmount, dailyCapIdr);
        }
        lateDeductionAmount = Math.round(lateDeductionAmount);
      }
      // Task 4.2 — Hitung nominal potongan alpha tidak hadir (persen × gaji / hari kerja default)
      let absenceDeductionAmount = 0;
      if (absentDays > 0 && lateCfg.absenceDailyPercentOfBasic > 0 && lateCfg.defaultWorkingDaysPerMonth > 0) {
        const perDayWageRate = baseMonthlyWage / lateCfg.defaultWorkingDaysPerMonth;
        const perDayDeduction = perDayWageRate * (lateCfg.absenceDailyPercentOfBasic / 100);
        absenceDeductionAmount = Math.round(perDayDeduction * absentDays);
      }

      const extraComponents: PayComponent[] = [];
      if (loanDeductionAmount > 0) {
        extraComponents.push({
          salaryComponentId: loanDeductionComponent.id,
          name: 'Potongan Pinjaman Karyawan',
          type: 'DEDUCTION',
          amount: loanDeductionAmount,
          isTaxable: false,
        });
      }
      if (overtimePayAmount > 0) {
        extraComponents.push({
          salaryComponentId: overtimeEarningComponent.id,
          name: 'Tunjangan Lembur',
          type: 'ALLOWANCE',
          amount: overtimePayAmount,
          isTaxable: true,
        });
      }
      if (lateDeductionAmount > 0) {
        extraComponents.push({
          salaryComponentId: lateDeductionComponent.id,
          name: 'Potongan Keterlambatan',
          type: 'DEDUCTION',
          amount: lateDeductionAmount,
          isTaxable: false,
        });
      }
      if (absenceDeductionAmount > 0) {
        extraComponents.push({
          salaryComponentId: absenceDeductionComponent.id,
          name: 'Potongan Tidak Hadir (Alpha)',
          type: 'DEDUCTION',
          amount: absenceDeductionAmount,
          isTaxable: false,
        });
      }
      const ewaDeductInfo = ewaDeductionByEmployee.get(salary.employeeId);
      const ewaDeductionAmount = ewaDeductInfo?.total.toNumber() ?? 0;
      if (ewaDeductionAmount > 0) {
        appliedEwaDeductions.push(...(ewaDeductInfo?.deductions ?? []));
        extraComponents.push({
          salaryComponentId: ewaDeductionComponent.id,
          name: 'Potongan EWA (Tarik Gaji Awal)',
          type: 'DEDUCTION',
          amount: ewaDeductionAmount,
          isTaxable: false,
        });
      }

      const emp = salary.employee;
      const taxContext = {
        married: emp?.maritalStatus === 'MARRIED',
        dependents: emp?._count?.families ?? 0,
        hasNpwp: Boolean(emp?.taxId),
      };

      const { earningsTotal, deductionsTotal, components, formulaCalculations } = calculateEmployeePay(salary, extraComponents, taxContext, {
        BASE_SALARY: salary.baseSalary.toString(), WORK_DAYS: String(workDaysInPeriod),
        PRESENT_DAYS: String(attd.present), LEAVE_DAYS: String(leaveDaysForEmployee),
        ABSENT_DAYS: String(absentDays), OVERTIME_HOURS: String(overtimeHoursForEmployee),
      }, formulaVersions);
      const netPay = new Prisma.Decimal(earningsTotal).minus(deductionsTotal).toDecimalPlaces(2).toNumber();
      if (netPay < 0) throw new BadRequestError('Payroll deductions exceed earnings; review the calculation before approval');

      // Create payslip
      const payslip = await payrollRepository.createPayslip({
        payrollRun: { connect: { id: runId } },
        employee: { connect: { id: salary.employeeId } },
        company: { connect: { id: run.companyId } },
        employeeSalary: { connect: { id: salary.id } },
        baseSalary: salary.baseSalary,
        totalEarnings: earningsTotal,
        totalDeductions: deductionsTotal,
        netPay,
        workDays: workDaysInPeriod,
        presentDays: attd.present,
        leaveDays: leaveDaysForEmployee,
        absentDays,
        overtimeHours: overtimeHoursForEmployee,
        status: 'DRAFT',
        formulaCalculations: { create: formulaCalculations.map(calculation => ({
          companyId: run.companyId, runId, componentId: calculation.componentId,
          versionId: calculation.versionId, expression: calculation.expression, amount: calculation.amount,
          inputs: calculation.inputs, dependencies: calculation.dependencies, engineVersion: calculation.engineVersion,
        })) },
        loanDeductionSnapshots: {
          create: dueLoanInstallments
            .filter(installment => installment.loan.employeeId === salary.employeeId)
            .map(installment => ({ companyId: run.companyId, runId,
              loanId: installment.loanId, installmentId: installment.id, amount: installment.amount })),
        },
      }, database);

      // Create payslip components
      if (components.length > 0) {
        await payrollRepository.createPayslipComponents(
          components.map((c) => ({
            payslipId: payslip.id,
            salaryComponentId: c.salaryComponentId,
            name: c.name,
            type: c.type,
            amount: c.amount,
            isTaxable: c.isTaxable,
          })), database
        );
      }

      totalEarnings = totalEarnings.plus(earningsTotal);
      totalDeductions = totalDeductions.plus(deductionsTotal);
      employeeCount++;
    }

    // Claim only EWA rows actually represented on a generated slip. Conditional
    // updates detect stale amounts/statuses; any failure rolls the entire run back.
    if (employeeCount === 0) throw new BadRequestError('No active employee salaries are available for this payroll');
    await ewaRepository.markPayrollDeductions(run.companyId, runId, appliedEwaDeductions, database);
    const totalNetPay = totalEarnings.minus(totalDeductions);
    for (const amount of [totalEarnings, totalDeductions, totalNetPay]) {
      if (!amount.isFinite() || amount.isNegative() || amount.greaterThan('9999999999999.99')) {
        throw new BadRequestError('Payroll totals exceed the supported monetary range');
      }
    }

    // Update run totals
    await payrollRepository.updatePayrollRunTotals(runId, {
      totalEmployees: employeeCount,
      totalEarnings,
      totalDeductions,
      totalNetPay,
    }, database);

    // Mark run as completed
    await payrollRepository.updatePayrollRunStatus(runId, 'COMPLETED', undefined, database);

  }

  private async ensureOvertimeEarningComponent(companyId: string, database: Prisma.TransactionClient) {
    const code = 'OVERTIME_EARNING_AUTO';
    const existing = await payrollRepository.findSalaryComponentByCode(companyId, code, database);
    if (existing) return existing;
    return payrollRepository.createSalaryComponent({
      companyId,
      name: 'Tunjangan Lembur',
      code,
      type: 'ALLOWANCE',
      calculationMethod: 'FIXED',
      amount: 0,
      isTaxable: true,
      isProrated: false,
      description: 'System generated: overtime pay per PP 35/2021',
      sortOrder: 998,
    }, database);
  }

  private async ensureLoanDeductionComponent(companyId: string, database: Prisma.TransactionClient) {
    const code = 'LOAN_DEDUCTION_AUTO';
    const existing = await payrollRepository.findSalaryComponentByCode(companyId, code, database);

    if (existing) {
      return existing;
    }

    return payrollRepository.createSalaryComponent({
      companyId,
      name: 'Potongan Pinjaman Karyawan',
      code,
      type: 'DEDUCTION',
      calculationMethod: 'FIXED',
      amount: 0,
      isTaxable: false,
      isProrated: false,
      description: 'System generated deduction for employee loan installments',
      sortOrder: 999,
    }, database);
  }

  private async ensureLateDeductionComponent(companyId: string, database: Prisma.TransactionClient) {
    const code = 'LATE_DEDUCTION_AUTO';
    const existing = await payrollRepository.findSalaryComponentByCode(companyId, code, database);
    if (existing) return existing;
    return payrollRepository.createSalaryComponent({
      companyId,
      name: 'Potongan Keterlambatan',
      code,
      type: 'DEDUCTION',
      calculationMethod: 'FIXED',
      amount: 0,
      isTaxable: false,
      isProrated: false,
      description: 'System generated: automatic late attendance deduction per minutes after branch tolerance',
      sortOrder: 997,
    }, database);
  }

  private async ensureAbsenceDeductionComponent(companyId: string, database: Prisma.TransactionClient) {
    const code = 'ABSENCE_DEDUCTION_AUTO';
    const existing = await payrollRepository.findSalaryComponentByCode(companyId, code, database);
    if (existing) return existing;
    return payrollRepository.createSalaryComponent({
      companyId,
      name: 'Potongan Tidak Hadir (Alpha)',
      code,
      type: 'DEDUCTION',
      calculationMethod: 'FIXED',
      amount: 0,
      isTaxable: false,
      isProrated: false,
      description: 'System generated: automatic absence per day deduction based on basic salary / working days',
      sortOrder: 996,
    }, database);
  }

  private async ensureEWADeductionComponent(companyId: string, database: Prisma.TransactionClient) {
    const code = 'EWA-DEDUCT';
    const existing = await payrollRepository.findSalaryComponentByCode(companyId, code, database);
    if (existing) return existing;
    return payrollRepository.createSalaryComponent({
      companyId,
      name: 'Potongan EWA (Tarik Gaji Awal)',
      code,
      type: 'DEDUCTION',
      calculationMethod: 'FIXED',
      amount: 0,
      isTaxable: false,
      isProrated: false,
      description: 'System generated: automatic deduction for approved Earned Wage Access paid requests (employer-funded float model). Deducted bulan berjalan di payslip.',
      sortOrder: 995,
    }, database);
  }

  // ==================== Standalone Calculation Endpoints (B.1, B.2, B.3) ====================

  calculatePph21Standalone(data: CalculatePph21DTO) {
    return calculatePph21({
      monthlyGross: data.monthlyGross,
      married: data.married,
      dependents: data.dependents,
      monthlyPensionContribution: data.monthlyPensionContribution,
      hasNpwp: data.hasNpwp,
    });
  }

  calculateThrStandalone(data: CalculateThrStandaloneDTO) {
    const result = calculateThr({
      monthlyWage: data.monthlyWage,
      joinDate: new Date(data.joinDate),
      referenceDate: data.referenceDate ? new Date(data.referenceDate) : new Date(),
    });
    // BONUS: hitung also PPh 21 untuk THR (aturan khusus THR: PPh dihitung tersendiri nanti)
    // Saat ini return amount THR saja sesuai acceptance B.2.
    return {
      ...result,
      monthlyWage: data.monthlyWage,
      joinDate: data.joinDate,
    };
  }

  calculateBpjsStandalone(data: CalculateBpjsDTO) {
    const baseRiskRate = JKK_RISK_TO_RATE[data.jkkRiskClass as JKKRiskClass];
    const mergedConfig = {
      jkkRatePercent: baseRiskRate,
      ...(data.customRates ?? {}),
    };
    const breakdown = calculateBpjs(data.monthlyWage, mergedConfig);
    return {
      jkkRiskClass: data.jkkRiskClass,
      configApplied: mergedConfig,
      ...breakdown,
    };
  }

  calculateJknStandalone(data: CalculateJknDTO) {
    const breakdown = calculateBpjs(data.monthlyWage, data.customRates ?? {});
    const base = Math.min(Math.max(0, data.monthlyWage), data.customRates?.jknWageCap ?? 12_000_000);
    return {
      monthlyWage: data.monthlyWage,
      jknBaseWage: base,
      configApplied: {
        jknEmployerPercent: data.customRates?.jknEmployerPercent ?? 4,
        jknEmployeePercent: data.customRates?.jknEmployeePercent ?? 1,
        jknWageCap: data.customRates?.jknWageCap ?? 12_000_000,
      },
      employee: { jkn: breakdown.employee.jkn },
      employer: { jkn: breakdown.employer.jkn },
      totalPerPerson: breakdown.employee.jkn + breakdown.employer.jkn,
    };
  }
}

export const payrollService = new PayrollService();
