import { payrollRepository } from './payroll.repository';
import {
  CreateSalaryComponentDTO,
  UpdateSalaryComponentDTO,
  CreateEmployeeSalaryDTO,
  UpdateEmployeeSalaryDTO,
  CreatePayrollPeriodDTO,
  UpdatePayrollPeriodDTO,
  CreatePayrollRunDTO,
} from './payroll.dto';
import { eventBus } from '@/shared/events/EventBus';
import { DomainEvents } from '@/shared/events/events';
import { logger } from '@/shared/logger/WinstonLogger';
import { NotFoundError, ConflictError, BadRequestError, ValidationError } from '@/shared/exceptions/AppError';
import { v4 as uuidv4 } from 'uuid';
import { employeeLoanRepository } from '@/modules/employee-loan/employee-loan.repository';
import { generateSystemCode } from '@/shared/utils/system-code';
import { calculateBpjs } from '@/shared/payroll/bpjs';
import { calculatePph21 } from '@/shared/payroll/pph21';
import { calculateThr } from '@/shared/payroll/thr';
import { prisma } from '@/shared/database/prisma';
import { calculateOvertimePay } from '@/shared/attendance/overtime';

export class PayrollService {
  // ==================== Salary Components ====================

  async findAllSalaryComponents(companyId: string) {
    return payrollRepository.findAllSalaryComponents(companyId);
  }

  async findSalaryComponentById(id: string) {
    const component = await payrollRepository.findSalaryComponentById(id);
    if (!component) throw new NotFoundError('Salary component not found');
    return component;
  }

  async createSalaryComponent(data: CreateSalaryComponentDTO) {
    const code = await generateSystemCode({
      prefix: 'PAY-CMP',
      label: data.name,
      exists: async (candidate) => Boolean(await payrollRepository.findSalaryComponentByCode(data.companyId, candidate)),
    });
    const existing = await payrollRepository.findSalaryComponentByCode(data.companyId, code);
    if (existing) throw new ConflictError('Salary component code already exists');

    const component = await payrollRepository.createSalaryComponent({ ...data, code });

    logger.info('Salary component created', { componentId: component.id, code: component.code });
    return component;
  }

  async updateSalaryComponent(id: string, data: UpdateSalaryComponentDTO) {
    const currentComponent = await this.findSalaryComponentById(id);
    const requestedCode = (data as Record<string, unknown>).code;
    if (typeof requestedCode === 'string' && requestedCode !== currentComponent.code) {
      throw new ValidationError('Salary component code is generated by system and cannot be changed');
    }
    const component = await payrollRepository.updateSalaryComponent(id, data);

    logger.info('Salary component updated', { componentId: id });
    return component;
  }

  async deleteSalaryComponent(id: string) {
    await this.findSalaryComponentById(id);
    await payrollRepository.softDeleteSalaryComponent(id);

    logger.info('Salary component deleted', { componentId: id });
  }

  // ==================== Employee Salaries ====================

  async findAllEmployeeSalaries(companyId: string, employeeId?: string) {
    return payrollRepository.findAllEmployeeSalaries(companyId, employeeId);
  }

  async findEmployeeSalaryById(id: string) {
    const salary = await payrollRepository.findEmployeeSalaryById(id);
    if (!salary) throw new NotFoundError('Employee salary not found');
    return salary;
  }

  async createEmployeeSalary(data: CreateEmployeeSalaryDTO) {
    // Deactivate existing active salary if any
    const existing = await payrollRepository.findActiveEmployeeSalary(data.employeeId);
    if (existing) {
      await payrollRepository.updateEmployeeSalary(existing.id, { isActive: false });
    }

    const salary = await payrollRepository.createEmployeeSalary(data);

    logger.info('Employee salary created', {
      employeeId: data.employeeId,
      salaryId: salary.id,
    });

    return salary;
  }

  async updateEmployeeSalary(id: string, data: UpdateEmployeeSalaryDTO) {
    await this.findEmployeeSalaryById(id);
    return payrollRepository.updateEmployeeSalary(id, data);
  }

  /**
   * Hitung THR seorang karyawan (Business Rule Gap: Permenaker 6/2016).
   * ≥12 bulan = 1× upah; 1–<12 bulan = prorata (masa kerja/12 × upah); <1 bulan = tidak berhak.
   */
  async calculateEmployeeThr(employeeId: string, referenceDate?: Date) {
    const { salary, employee } = await payrollRepository.findThrInputs(employeeId);
    if (!employee) throw new NotFoundError('Employee not found');
    if (!employee.joinDate) {
      throw new BadRequestError('Tanggal masuk (joinDate) karyawan belum diisi');
    }
    if (!salary) {
      throw new BadRequestError('Data gaji aktif karyawan tidak ditemukan');
    }

    const result = calculateThr({
      monthlyWage: Number(salary.baseSalary),
      joinDate: employee.joinDate,
      referenceDate: referenceDate ?? new Date(),
    });

    logger.info('THR calculated', { employeeId, tenureMonths: result.tenureMonths, amount: result.amount });

    return {
      employee: { id: employee.id, fullName: employee.fullName, employeeNumber: employee.employeeNumber },
      monthlyWage: Number(salary.baseSalary),
      ...result,
    };
  }

  // ==================== Payroll Periods ====================

  async findAllPayrollPeriods(companyId: string) {
    return payrollRepository.findAllPayrollPeriods(companyId);
  }

  async findPayrollPeriodById(id: string) {
    const period = await payrollRepository.findPayrollPeriodById(id);
    if (!period) throw new NotFoundError('Payroll period not found');
    return period;
  }

  async createPayrollPeriod(data: CreatePayrollPeriodDTO) {
    const code = await generateSystemCode({
      prefix: 'PAY-PRD',
      label: data.name,
      exists: async (candidate) => {
        const periods = await payrollRepository.findAllPayrollPeriods(data.companyId);
        return periods.some((period) => period.code === candidate);
      },
    });
    const period = await payrollRepository.createPayrollPeriod({ ...data, code });

    logger.info('Payroll period created', { periodId: period.id, code: period.code });
    return period;
  }

  async closePayrollPeriod(id: string) {
    await this.findPayrollPeriodById(id);
    const period = await payrollRepository.closePayrollPeriod(id);

    logger.info('Payroll period closed', { periodId: id });
    return period;
  }

  async updatePayrollPeriod(id: string, data: UpdatePayrollPeriodDTO) {
    const period = await this.findPayrollPeriodById(id);
    const requestedCode = (data as Record<string, unknown>).code;
    if (typeof requestedCode === 'string' && requestedCode !== period.code) {
      throw new ValidationError('Payroll period code is generated by system and cannot be changed');
    }
    if (period.status === 'CLOSED') {
      throw new BadRequestError('Cannot update a closed payroll period');
    }
    return payrollRepository.updatePayrollPeriod(id, data);
  }

  // ==================== Payroll Runs ====================

  async findAllPayrollRuns(companyId: string) {
    return payrollRepository.findAllPayrollRuns(companyId);
  }

  async findPayrollRunById(id: string) {
    const run = await payrollRepository.findPayrollRunById(id);
    if (!run) throw new NotFoundError('Payroll run not found');
    return run;
  }

  async createPayrollRun(data: CreatePayrollRunDTO, userId?: string) {
    // Validate period exists and is not closed
    const period = await this.findPayrollPeriodById(data.periodId);
    if (period.status === 'CLOSED') {
      throw new BadRequestError('Cannot create payroll run for a closed period');
    }

    // Get run number
    const lastRunNumber = await payrollRepository.findLatestRunNumber(data.companyId);
    const runNumber = lastRunNumber + 1;

    // Create run
    const run = await payrollRepository.createPayrollRun(data, runNumber);

    // Run payroll calculation
    await this.calculatePayroll(run.id);

    // Publish event
    await eventBus.publish({
      name: DomainEvents.PAYROLL_RUN_CREATED,
      aggregateId: run.id,
      aggregateType: 'PayrollRun',
      data: { runNumber, companyId: data.companyId, periodId: data.periodId },
      metadata: {
        eventId: uuidv4(),
        occurredAt: new Date(),
      },
    });

    logger.info('Payroll run created', { runId: run.id, runNumber });
    return this.findPayrollRunById(run.id);
  }

  async approvePayrollRun(id: string, userId: string) {
    const run = await this.findPayrollRunById(id);
    if (run.status !== 'COMPLETED') {
      throw new BadRequestError('Only completed payroll runs can be approved');
    }

    const approved = await payrollRepository.updatePayrollRunStatus(id, 'APPROVED', userId);

    await eventBus.publish({
      name: DomainEvents.PAYROLL_RUN_APPROVED,
      aggregateId: id,
      aggregateType: 'PayrollRun',
      data: { approvedBy: userId },
      metadata: {
        eventId: uuidv4(),
        occurredAt: new Date(),
      },
    });

    return approved;
  }

  async disbursePayrollRun(id: string, userId: string) {
    const run = await this.findPayrollRunById(id);
    if (run.status !== 'APPROVED') {
      throw new BadRequestError('Only approved payroll runs can be disbursed');
    }

    const employeeIds = Array.from(new Set((run.payslips || []).map((payslip) => payslip.employeeId)));
    await employeeLoanRepository.applyPayrollDeductions(
      run.companyId,
      employeeIds,
      new Date(run.period.endDate),
      new Date(),
      run.runNumber
    );

    const disbursed = await payrollRepository.updatePayrollRunStatus(id, 'DISBURSED', userId);

    await eventBus.publish({
      name: DomainEvents.PAYROLL_RUN_DISBURSED,
      aggregateId: id,
      aggregateType: 'PayrollRun',
      data: { disbursedBy: userId },
      metadata: {
        eventId: uuidv4(),
        occurredAt: new Date(),
      },
    });

    return disbursed;
  }

  // ==================== Payslips ====================

  async findPayslipById(id: string) {
    const payslip = await payrollRepository.findPayslipById(id);
    if (!payslip) throw new NotFoundError('Payslip not found');
    return payslip;
  }

  async findPayslipsByEmployee(employeeId: string) {
    return payrollRepository.findPayslipsByEmployee(employeeId);
  }

  // ==================== Payroll Calculation ====================

  private async calculatePayroll(runId: string) {
    const run = await payrollRepository.findPayrollRunById(runId);
    if (!run) throw new NotFoundError('Payroll run not found');

    // Get all employees with active salary in this company
    const employeeSalaries = await payrollRepository.findAllEmployeeSalaries(run.companyId);
    const loanDeductionComponent = await this.ensureLoanDeductionComponent(run.companyId);
    const overtimeEarningComponent = await this.ensureOvertimeEarningComponent(run.companyId);
    const dueLoanInstallments = await employeeLoanRepository.findDueInstallmentsForPayroll(
      run.companyId,
      new Date(run.period.endDate)
    );
    const loanDeductionByEmployee = dueLoanInstallments.reduce<Record<string, number>>((acc, installment) => {
      const employeeId = installment.loan.employeeId;
      acc[employeeId] = (acc[employeeId] || 0) + Number(installment.amount);
      return acc;
    }, {});

    // Aggregate approved overtime hours per employee within the pay period
    const approvedOvertimes = await prisma.overtimeRequest.findMany({
      where: {
        companyId: run.companyId,
        status: 'APPROVED',
        date: { gte: new Date(run.period.startDate), lte: new Date(run.period.endDate) },
        deletedAt: null,
      },
      select: { employeeId: true, durationHours: true },
    });
    const overtimeHoursByEmployee = approvedOvertimes.reduce<Record<string, number>>((acc, ot) => {
      acc[ot.employeeId] = (acc[ot.employeeId] || 0) + Number(ot.durationHours);
      return acc;
    }, {});

    // Delete existing payslips for this run (recalculation)
    await payrollRepository.deletePayslipsByRunId(runId);

    let totalEarnings = 0;
    let totalDeductions = 0;
    let employeeCount = 0;

    for (const salary of employeeSalaries) {
      if (!salary.isActive) continue;

      const loanDeductionAmount = loanDeductionByEmployee[salary.employeeId] || 0;
      const overtimeHoursForEmployee = overtimeHoursByEmployee[salary.employeeId] || 0;
      const overtimePayAmount = overtimeHoursForEmployee > 0
        ? calculateOvertimePay({ monthlyWage: Number(salary.baseSalary), hours: overtimeHoursForEmployee, dayType: 'WORKDAY' }).amount
        : 0;

      const extraComponents: Array<{ salaryComponentId: string; name: string; type: string; amount: number; isTaxable: boolean }> = [];
      if (loanDeductionAmount > 0) {
        extraComponents.push({
          salaryComponentId: loanDeductionComponent.id,
          name: 'Potongan Pinjaman Karyawan',
          type: 'DEDUCTION',
          amount: loanDeductionAmount,
          isTaxable: false,
        });
      }
      if (overtimePayAmount > 0) {
        extraComponents.push({
          salaryComponentId: overtimeEarningComponent.id,
          name: 'Tunjangan Lembur',
          type: 'ALLOWANCE',
          amount: overtimePayAmount,
          isTaxable: true,
        });
      }

      const emp = salary.employee as { maritalStatus?: string | null; taxId?: string | null; _count?: { families: number } };
      const taxContext = {
        married: emp?.maritalStatus === 'MARRIED',
        dependents: emp?._count?.families ?? 0,
        hasNpwp: Boolean(emp?.taxId),
      };

      const { earningsTotal, deductionsTotal, components } = this.calculateEmployeePay(salary, extraComponents, taxContext);
      const netPay = earningsTotal - deductionsTotal;

      // Create payslip
      const payslip = await payrollRepository.createPayslip({
        payrollRun: { connect: { id: runId } },
        employee: { connect: { id: salary.employeeId } },
        company: { connect: { id: run.companyId } },
        employeeSalary: { connect: { id: salary.id } },
        baseSalary: salary.baseSalary,
        totalEarnings: earningsTotal,
        totalDeductions: deductionsTotal,
        netPay,
        workDays: 0,
        presentDays: 0,
        leaveDays: 0,
        absentDays: 0,
        overtimeHours: overtimeHoursForEmployee,
        status: 'DRAFT',
      });

      // Create payslip components
      if (components.length > 0) {
        await payrollRepository.createPayslipComponents(
          components.map((c) => ({
            payslipId: payslip.id,
            salaryComponentId: c.salaryComponentId,
            name: c.name,
            type: c.type as any,
            amount: c.amount,
            isTaxable: c.isTaxable,
          }))
        );
      }

      totalEarnings += earningsTotal;
      totalDeductions += deductionsTotal;
      employeeCount++;
    }

    // Update run totals
    await payrollRepository.updatePayrollRunTotals(runId, {
      totalEmployees: employeeCount,
      totalEarnings,
      totalDeductions,
      totalNetPay: totalEarnings - totalDeductions,
    });

    // Mark run as completed
    await payrollRepository.updatePayrollRunStatus(runId, 'COMPLETED');

    logger.info('Payroll calculation completed', {
      runId,
      employeeCount,
      totalEarnings,
      totalDeductions,
    });
  }

  private async ensureOvertimeEarningComponent(companyId: string) {
    const code = 'OVERTIME_EARNING_AUTO';
    const existing = await payrollRepository.findSalaryComponentByCode(companyId, code);
    if (existing) return existing;
    return payrollRepository.createSalaryComponent({
      companyId,
      name: 'Tunjangan Lembur',
      code,
      type: 'ALLOWANCE',
      calculationMethod: 'FIXED',
      amount: 0,
      isTaxable: true,
      isProrated: false,
      description: 'System generated: overtime pay per PP 35/2021',
      sortOrder: 998,
    });
  }

  private async ensureLoanDeductionComponent(companyId: string) {
    const code = 'LOAN_DEDUCTION_AUTO';
    const existing = await payrollRepository.findSalaryComponentByCode(companyId, code);

    if (existing) {
      return existing;
    }

    return payrollRepository.createSalaryComponent({
      companyId,
      name: 'Potongan Pinjaman Karyawan',
      code,
      type: 'DEDUCTION',
      calculationMethod: 'FIXED',
      amount: 0,
      isTaxable: false,
      isProrated: false,
      description: 'System generated deduction for employee loan installments',
      sortOrder: 999,
    });
  }

  private calculateEmployeePay(
    salary: any,
    extraComponents: Array<{
      salaryComponentId: string;
      name: string;
      type: string;
      amount: number;
      isTaxable: boolean;
    }> = [],
    taxContext?: { married: boolean; dependents: number; hasNpwp: boolean }
  ) {
    const wage = Number(salary.baseSalary);

    // Pass 1: resolve each active component's amount (percentage on base wage).
    const resolved = (salary.components as any[])
      .filter((c) => c.isActive)
      .map((comp) => {
        const sc = comp.salaryComponent;
        let amount = Number(comp.amount);
        if (sc.calculationMethod === 'PERCENTAGE' && sc.ratePercent) {
          amount = wage * (Number(sc.ratePercent) / 100);
        }
        return {
          code: sc.code as string,
          entry: {
            salaryComponentId: sc.id,
            name: sc.name,
            type: sc.type as any,
            amount,
            isTaxable: sc.isTaxable,
          },
        };
      });

    // Task 2.6/2.7: statutory engines replace the naive flat-rate components.
    const taxableGross = resolved
      .filter((r) => r.entry.type === 'ALLOWANCE' && r.entry.isTaxable)
      .reduce((sum, r) => sum + r.entry.amount, 0);
    const bpjs = calculateBpjs(wage);
    const pension = bpjs.employee.jht + bpjs.employee.jp; // deductible from PPh21 gross
    const pph = taxContext
      ? calculatePph21({
          monthlyGross: taxableGross,
          married: taxContext.married,
          dependents: taxContext.dependents,
          monthlyPensionContribution: pension,
          hasNpwp: taxContext.hasNpwp,
        })
      : null;

    for (const r of resolved) {
      if (r.code === 'BPJS-TK') r.entry.amount = bpjs.employee.jht + bpjs.employee.jp;
      else if (r.code === 'BPJS-KES') r.entry.amount = bpjs.employee.jkn;
      else if (r.code === 'PPH21' && pph) r.entry.amount = pph.monthlyTax;
    }

    let earningsTotal = 0;
    let deductionsTotal = 0;
    const components = resolved.map((r) => r.entry);
    for (const r of resolved) {
      if (r.entry.type === 'ALLOWANCE') earningsTotal += r.entry.amount;
      else deductionsTotal += r.entry.amount;
    }

    for (const comp of extraComponents) {
      components.push(comp);
      if (comp.type === 'ALLOWANCE') earningsTotal += comp.amount;
      else deductionsTotal += comp.amount;
    }

    return { earningsTotal, deductionsTotal, components };
  }
}

export const payrollService = new PayrollService();
