import { roleRepository, permissionRepository } from './rbac.repository';
import { eventBus } from '@/shared/events/EventBus';
import { DomainEvents } from '@/shared/events/events';
import { WinstonLogger } from '@/shared/logger/WinstonLogger';
import {
  NotFoundError,
  ConflictError,
  ValidationError,
  ForbiddenError,
} from '@/shared/exceptions/AppError';
import {
  CreateRoleDTO,
  UpdateRoleDTO,
  AssignPermissionsDTO,
  AssignUserRolesDTO,
} from './rbac.dto';
import prisma from '@/shared/database/prisma';
import { randomUUID as uuidv4 } from 'node:crypto';
import { generateSystemCode } from '@/shared/utils/system-code';
import { cached, invalidateKeys, cacheKey, CACHE_TTL } from '@/shared/cache/cacheAside';

const logger = new WinstonLogger('RBACService');

// Task 2.1: role lists are invalidated by exact key on mutation.
const rolesKey = (companyId?: string | null) => cacheKey(companyId ?? 'global', 'roles');
const invalidateRoles = (companyId?: string | null) =>
  invalidateKeys(rolesKey(companyId), rolesKey('global'));

export class RoleService {
  async findAll(companyId?: string, groupId?: string) {
    // Only the common (company-scoped, no group filter) list is cached.
    if (groupId) return roleRepository.findAll(companyId, groupId);
    return cached(rolesKey(companyId), CACHE_TTL.static, () => roleRepository.findAll(companyId));
  }

  async findById(id: string) {
    const role = await roleRepository.findById(id);
    if (!role) throw new NotFoundError('Role not found');
    return role;
  }

  async create(dto: CreateRoleDTO) {
    const code = await generateSystemCode({
      prefix: 'ROLE',
      label: dto.name,
      exists: async (candidate) => Boolean(await roleRepository.findByCode(candidate)),
    });

    const existing = await roleRepository.findByCode(code);
    if (existing) throw new ConflictError(`Role code "${code}" already exists`);

    this.validateScope(dto);

    const role = await roleRepository.create({
      ...dto,
      code,
    });

    await invalidateRoles(dto.companyId);

    await eventBus.publish({
      name: DomainEvents.ROLE_CREATED,
      aggregateId: role.id,
      aggregateType: 'Role',
      data: dto,
      metadata: { eventId: uuidv4(), occurredAt: new Date() },
    });

    return role;
  }

  async update(id: string, dto: UpdateRoleDTO) {
    const role = await this.findById(id);

    if (role.isSystem) {
      throw new ValidationError('System roles cannot be modified');
    }

    this.validateImmutableScope(role, dto);

    if (dto.code && dto.code !== role.code) {
      throw new ValidationError('Role code is generated by system and cannot be changed');
    }

    if (dto.code === role.code) {
      delete dto.code;
    }

    if (dto.name && dto.name.trim() === role.name) {
      delete dto.name;
    }

    if (dto.description !== undefined && dto.description === role.description) {
      delete dto.description;
    }

    if (dto.priority !== undefined && dto.priority === role.priority) {
      delete dto.priority;
    }

    this.validateScope(dto);

    const updated = await roleRepository.update(id, dto);

    await invalidateRoles(role.companyId);

    await eventBus.publish({
      name: DomainEvents.ROLE_UPDATED,
      aggregateId: id,
      aggregateType: 'Role',
      data: dto,
      metadata: { eventId: uuidv4(), occurredAt: new Date() },
    });

    return updated;
  }

  async delete(id: string) {
    const role = await this.findById(id);
    if (role.isSystem) {
      throw new ValidationError('System roles cannot be deleted');
    }
    await roleRepository.softDelete(id);

    await invalidateRoles(role.companyId);

    await eventBus.publish({
      name: DomainEvents.ROLE_DELETED,
      aggregateId: id,
      aggregateType: 'Role',
      data: {},
      metadata: { eventId: uuidv4(), occurredAt: new Date() },
    });
  }

  async getPermissions(roleId: string) {
    await this.findById(roleId);
    return permissionRepository.getRolePermissions(roleId);
  }

  async assignPermissions(roleId: string, dto: AssignPermissionsDTO) {
    const role = await this.findById(roleId);

    if (role.isSystem) {
      throw new ValidationError('System role permissions cannot be modified');
    }

    // Verify all permissions exist
    const permissions = await permissionRepository.findByIds(dto.permissionIds);
    if (permissions.length !== dto.permissionIds.length) {
      throw new NotFoundError('One or more permissions not found');
    }

    await permissionRepository.assignToRole(roleId, dto.permissionIds);

    await eventBus.publish({
      name: DomainEvents.PERMISSION_ASSIGNED,
      aggregateId: roleId,
      aggregateType: 'Role',
      data: { permissionIds: dto.permissionIds },
      metadata: { eventId: uuidv4(), occurredAt: new Date() },
    });

    logger.info(`Permissions assigned to role ${role.name}: ${dto.permissionIds.length} permissions`);
    return permissionRepository.getRolePermissions(roleId);
  }

  async assignToUser(
    userId: string,
    dto: AssignUserRolesDTO,
    requesterId: string,
    requesterCtx?: {
      companyScope: string[];
      groupId?: string | null;
      maxRolePriority: number;
      hasGlobalRole: boolean;
    },
  ) {
    // ======================================================
    // Finding #1: RBAC Privilege Escalation FULL GUARD CHAIN
    // (1) GLOBAL scope assign butuh requester GLOBAL role (existing guard, dipertahankan)
    // (2) Target user harus berada dalam jangkauan scope manageability requester
    // (3) COMPANY/GROUP scopeId tidak boleh client-controlled → WAJIB ada di requester scope list
    // (4) Priority hierarki: max priority role yang di-assign ≤ max priority requester (tidak bisa promote lebih tinggi dari diri sendiri!)
    // (5) DeleteMany existing userRole juga di-scoped (tidak hapus role beda scope yang tidak boleh dipegang requester)
    // ======================================================

    // (1) Existing guard GLOBAL-scope assignment.
    if (dto.scopeType === 'GLOBAL') {
      const requesterRoles = await prisma.userRole.findFirst({
        where: { userId: requesterId, role: { scope: 'GLOBAL', deletedAt: null } },
        select: { id: true },
      });
      if (!requesterRoles) {
        throw new ForbiddenError('Only users with a GLOBAL-scope role may assign GLOBAL-scope roles');
      }
    }

    // Pre-fetch requester hierarchy + scope if controller tidak kasih (defensive code path)
    const reqCtx: NonNullable<typeof requesterCtx> = requesterCtx ?? (await this.buildRequesterCtx(requesterId));

    // Pre-fetch roles dengan priority + scope untuk guard (3) dan (4)
    const roles = await prisma.role.findMany({
      where: { id: { in: dto.roleIds }, deletedAt: null },
      select: { id: true, scope: true, priority: true, code: true, companyId: true, groupId: true },
    });
    if (roles.length !== new Set(dto.roleIds).size) {
      const found = new Set(roles.map((r) => r.id));
      const missing = dto.roleIds.find((id) => !found.has(id));
      throw new NotFoundError(`Role ${missing} not found`);
    }

    // Prevent assigning GLOBAL-scoped role objects unless requester has GLOBAL scope.
    const hasGlobalRole = roles.some((r) => r.scope === 'GLOBAL');
    if (hasGlobalRole && dto.scopeType !== 'GLOBAL') {
      throw new ValidationError('Cannot assign a GLOBAL-scoped role with a non-GLOBAL scopeType');
    }

    // GUARD (4): Hierarchy priority. Requester tidak boleh assign role yang LEBIH TINGGI (lebih kecil priority number? atau lebih besar? Sesuai convention priority = semakin besar semakin tinggi privilege. Kita enforce: max(role.priority) ≤ reqCtx.maxRolePriority)
    const maxAssignedPriority = Math.max(...roles.map((r) => Number(r.priority ?? 0)));
    if (!reqCtx.hasGlobalRole && maxAssignedPriority > reqCtx.maxRolePriority) {
      throw new ForbiddenError(
        `Cannot assign roles with higher hierarchy (priority ${maxAssignedPriority}) than your own max priority ${reqCtx.maxRolePriority}`,
      );
    }

    // GUARD (2): Target user harus dalam scope manageability requester.
    // Cari data target user: employee.companyId, employee.company.groupId
    const targetUser = await prisma.user.findUnique({
      where: { id: userId },
      select: {
        id: true,
        employee: { select: { companyId: true, company: { select: { groupId: true } } } },
      },
    });
    if (!targetUser) throw new NotFoundError('Target user not found');
    const targetCompanyId = targetUser.employee?.companyId ?? null;
    const targetGroupId = targetUser.employee?.company?.groupId ?? null;
    if (!reqCtx.hasGlobalRole) {
      // GROUP_ADMIN scope: target groupId harus cocok / companyId dalam daftar group perusahaan dia
      if (reqCtx.groupId && targetGroupId && targetGroupId !== reqCtx.groupId) {
        throw new ForbiddenError('Target user berada di luar company group akses Anda');
      }
      // COMPANY_ADMIN scope: targetCompanyId WAJIB ada di companyScope requester
      if (dto.scopeType === 'COMPANY' && targetCompanyId && !reqCtx.companyScope.includes(targetCompanyId)) {
        throw new ForbiddenError('Anda tidak memiliki wewenang untuk manage user di company tersebut');
      }
      // GROUP scope assign: targetGroupId harus == dto.groupId (sudah ada validasi dibawah) dan requester punya group scope
      if (dto.scopeType === 'GROUP' && targetGroupId && dto.groupId && targetGroupId !== dto.groupId) {
        throw new ForbiddenError('Target user berada di luar group yang dituju');
      }
    }

    // GUARD (3): COMPANY_ID / GROUP_ID DI DTO TIDAK BOLEH CLIENT-CONTROLLED SEMBARANG!
    // Wajib match dengan scope list yang dimiliki requester.
    if (!reqCtx.hasGlobalRole) {
      if (dto.scopeType === 'COMPANY') {
        const resolvedCompanyId = dto.companyId ?? targetCompanyId;
        if (!resolvedCompanyId) {
          throw new ValidationError('Company-scoped role assignment requires companyId context');
        }
        if (!reqCtx.companyScope.includes(resolvedCompanyId)) {
          throw new ForbiddenError('companyId pada role assignment berada di luar daftar akses perusahaan Anda');
        }
        dto.companyId = resolvedCompanyId; // Overwrite pasti (client kirim salah juga akan paksa ke yang valid)
        // GUARD tambahan: Role object sendiri kalau COMPANY scoped harusnya milik company itu
        for (const r of roles) {
          if (r.scope === 'COMPANY' && r.companyId && r.companyId !== resolvedCompanyId) {
            throw new ForbiddenError(`Role ${r.code} tidak tersedia untuk company ${resolvedCompanyId}`);
          }
          if (r.scope === 'GROUP' && r.groupId && reqCtx.groupId && r.groupId !== reqCtx.groupId) {
            throw new ForbiddenError(`Role ${r.code} berada di group lain`);
          }
        }
      } else if (dto.scopeType === 'GROUP') {
        const resolvedGroupId = dto.groupId ?? reqCtx.groupId ?? targetGroupId;
        if (!resolvedGroupId) {
          throw new ValidationError('Group-scoped role assignment requires groupId context');
        }
        if (reqCtx.groupId && resolvedGroupId !== reqCtx.groupId) {
          throw new ForbiddenError('groupId pada role assignment berada di luar group akses Anda');
        }
        dto.groupId = resolvedGroupId;
      }
    }

    // GUARD tambahan: Company-scoped role objects wajib punya companyId bind yang konsisten
    if (dto.scopeType === 'COMPANY' && !dto.companyId && !reqCtx.hasGlobalRole) {
      throw new ValidationError('Company-scoped role assignment missing companyId binding');
    }
    if (dto.scopeType === 'GROUP' && !dto.groupId && !reqCtx.hasGlobalRole) {
      throw new ValidationError('Group-scoped role assignment missing groupId binding');
    }

    // (5) Scoped remove existing roles — HANYA hapus role yang dalam scope yang di-manage requester.
    // JANGAN sampai COMPANY_ADMIN A hapus GLOBAL role SUPER_ADMIN pada user secara tidak sengaja / serangan!
    if (reqCtx.hasGlobalRole) {
      // SUPER_ADMIN boleh hapus semua role pada target
      await prisma.userRole.deleteMany({ where: { userId } });
    } else {
      // Hanya hapus role di scopeType yang sedang di-process / scope company/grup requester
      await prisma.userRole.deleteMany({
        where: {
          userId,
          OR: [
            { scopeType: dto.scopeType as any, companyId: dto.companyId ?? undefined, groupId: dto.groupId ?? undefined },
            ...(dto.scopeType === 'COMPANY'
              ? [{ companyId: { in: reqCtx.companyScope } }]
              : dto.scopeType === 'GROUP' && reqCtx.groupId
                ? [{ groupId: reqCtx.groupId }]
                : []),
          ],
        },
      });
    }

    // Assign new roles (scoped company/group sesuai DTO yang sudah di-validasi & di-overwrite guard 3)
    const userRoles = await prisma.userRole.createMany({
      data: dto.roleIds.map((roleId) => ({
        userId,
        roleId,
        companyId: dto.scopeType === 'COMPANY' ? dto.companyId ?? null : dto.scopeType === 'GLOBAL' ? null : undefined,
        groupId: dto.scopeType === 'GROUP' ? dto.groupId ?? null : dto.scopeType === 'GLOBAL' ? null : undefined,
        scopeType: dto.scopeType as any,
      })),
    });

    await eventBus.publish({
      name: DomainEvents.ROLE_ASSIGNED,
      aggregateId: userId,
      aggregateType: 'User',
      data: { roleIds: dto.roleIds, scopeType: dto.scopeType, companyId: dto.companyId, groupId: dto.groupId, requesterId },
      metadata: { eventId: uuidv4(), occurredAt: new Date(), correlationId: requesterId },
    });

    // Invalidate cache user tersebut (karena role diganti → token refresh)
    invalidateKeys(cacheKey(userId, 'user-context'));

    return userRoles;
  }

  /**
   * Finding #1 helper: Build requester RBAC hierarchy context (for controllers/service defensive code).
   * Dipanggil otomatis oleh assignToUser jika controller tidak mengirim explicit ctx.
   */
  private async buildRequesterCtx(
    requesterId: string,
  ): Promise<{ companyScope: string[]; groupId?: string | null; maxRolePriority: number; hasGlobalRole: boolean }> {
    const requesterUserRoles = await prisma.userRole.findMany({
      where: { userId: requesterId, role: { deletedAt: null } },
      include: { role: { select: { scope: true, priority: true, companyId: true, groupId: true } } },
    });
    const hasGlobalRole = requesterUserRoles.some((ur) => ur.role.scope === 'GLOBAL');
    const maxRolePriority = Math.max(0, ...requesterUserRoles.map((ur) => Number(ur.role.priority ?? 0)));
    const companyScope = Array.from(
      new Set(
        requesterUserRoles
          .filter((ur) => ur.companyId || ur.role.companyId)
          .map((ur) => (ur.companyId ?? ur.role.companyId) as string)
          .filter(Boolean),
      ),
    );
    const groupId = requesterUserRoles.find((ur) => ur.groupId || ur.role.groupId)?.groupId ??
      requesterUserRoles.find((ur) => ur.groupId || ur.role.groupId)?.role?.groupId ??
      null;
    return { companyScope, groupId, maxRolePriority, hasGlobalRole };
  }

  async getUserRoles(userId: string) {
    return prisma.userRole.findMany({
      where: { userId },
      include: {
        role: {
          include: {
            _count: { select: { rolePermissions: true } },
          },
        },
      },
    });
  }

  private validateScope(dto: Partial<CreateRoleDTO>): void {
    if (dto.scope === 'GLOBAL' && dto.companyId) {
      throw new ValidationError('Global roles cannot be scoped to a company');
    }
    if (dto.scope === 'COMPANY' && !dto.companyId) {
      throw new ValidationError('Company-scoped roles must have a companyId');
    }
    if (dto.scope === 'GROUP' && !dto.groupId) {
      throw new ValidationError('Group-scoped roles must have a groupId');
    }
  }

  private validateImmutableScope(
    role: { scope: string; companyId?: string | null; groupId?: string | null },
    dto: UpdateRoleDTO
  ): void {
    if (dto.scope && dto.scope !== role.scope) {
      throw new ValidationError('Role scope cannot be changed after creation');
    }

    if (dto.companyId !== undefined && dto.companyId !== (role.companyId ?? undefined)) {
      throw new ValidationError('Role company binding cannot be changed after creation');
    }

    if (dto.groupId !== undefined && dto.groupId !== (role.groupId ?? undefined)) {
      throw new ValidationError('Role group binding cannot be changed after creation');
    }
  }
}

export const roleService = new RoleService();

export class PermissionService {
  // Permissions are seeded and immutable at runtime — TTL-only cache, no invalidation.
  async findAll(module?: string) {
    return cached(cacheKey(module ?? 'all', 'permissions'), CACHE_TTL.static, () =>
      permissionRepository.findAll(module)
    );
  }

  async getUserPermissions(userId: string) {
    return permissionRepository.getUserPermissions(userId);
  }
}

export const permissionService = new PermissionService();
