import { createRoleSchema, updateRoleSchema } from './rbac.dto';

/**
 * Role codes are the one item from the tenant-scoped-codes audit that stays
 * server-owned (DECISIONS.md D-006). The contract has to say so: the field used
 * to be accepted and then dropped without a word, which is the behaviour this
 * pins against coming back.
 */
describe('role code is not a client-settable field', () => {
  const payload = { companyId: '11111111-1111-4111-8111-111111111111', name: 'Supervisor' };

  it('accepts a role without a code', () => {
    const parsed = createRoleSchema.parse(payload);

    expect(parsed).toMatchObject({ name: 'Supervisor', scope: 'COMPANY', priority: 0 });
    expect(parsed.code).toBeUndefined();
  });

  it('refuses a client-sent code out loud instead of dropping it', () => {
    const result = createRoleSchema.safeParse({ ...payload, code: 'SUPERVISOR' });

    expect(result.success).toBe(false);
    if (result.success) return;
    const issue = result.error.issues.find((i) => i.path.join('.') === 'code');
    expect(issue?.message).toBe('Role code is generated by the system and cannot be set');
  });

  it('refuses it on update too', () => {
    const result = updateRoleSchema.safeParse({ name: 'Supervisor', code: 'SUPERVISOR' });

    expect(result.success).toBe(false);
  });

  it('still lets an update through when it leaves the code alone', () => {
    const result = updateRoleSchema.safeParse({ name: 'Supervisor', priority: 3 });

    expect(result.success).toBe(true);
  });
});
