import { z } from 'zod';

export const createRoleSchema = z.object({
  companyId: z.string().uuid().optional(),
  groupId: z.string().uuid().optional(),
  name: z.string().min(2, 'Role name must be at least 2 characters').max(255),
  // A role code is machinery, not customer data: the RBAC seeds and every
  // platform-level role (`companyId: null`) key on it, and `roles.code` stays
  // unique across the installation because MySQL cannot enforce "unique per
  // company plus unique among the platform rows" with one composite index.
  // The field used to be accepted here and then dropped in silence; now it is
  // refused out loud. See DECISIONS.md D-006.
  code: z.undefined({ invalid_type_error: 'Role code is generated by the system and cannot be set' }).optional(),
  description: z.string().optional(),
  scope: z.enum(['GLOBAL', 'GROUP', 'COMPANY']).default('COMPANY'),
  priority: z.number().int().min(0).default(0),
});

export const updateRoleSchema = createRoleSchema.partial();

export const assignPermissionsSchema = z.object({
  permissionIds: z.array(z.string().uuid()).min(1, 'At least one permission is required'),
});

export const assignUserRolesSchema = z.object({
  roleIds: z.array(z.string().uuid()).min(1, 'At least one role is required'),
  companyId: z.string().uuid().optional(),
  groupId: z.string().uuid().optional(),
  scopeType: z.enum(['GLOBAL', 'GROUP', 'COMPANY']).default('COMPANY'),
});

export type CreateRoleDTO = z.infer<typeof createRoleSchema>;
export type UpdateRoleDTO = z.infer<typeof updateRoleSchema>;
export type AssignPermissionsDTO = z.infer<typeof assignPermissionsSchema>;
export type AssignUserRolesDTO = z.infer<typeof assignUserRolesSchema>;
