import { roleRepository, permissionRepository } from './rbac.repository';
import { eventBus } from '@/shared/events/EventBus';
import { DomainEvents } from '@/shared/events/events';
import { WinstonLogger } from '@/shared/logger/WinstonLogger';
import {
  NotFoundError,
  ConflictError,
  ValidationError,
} from '@/shared/exceptions/AppError';
import {
  CreateRoleDTO,
  UpdateRoleDTO,
  AssignPermissionsDTO,
  AssignUserRolesDTO,
} from './rbac.dto';
import prisma from '@/shared/database/prisma';
import { v4 as uuidv4 } from 'uuid';
import { generateSystemCode } from '@/shared/utils/system-code';
import { cached, invalidateKeys, cacheKey, CACHE_TTL } from '@/shared/cache/cacheAside';

const logger = new WinstonLogger('RBACService');

// Task 2.1: role lists are invalidated by exact key on mutation.
const rolesKey = (companyId?: string | null) => cacheKey(companyId ?? 'global', 'roles');
const invalidateRoles = (companyId?: string | null) =>
  invalidateKeys(rolesKey(companyId), rolesKey('global'));

export class RoleService {
  async findAll(companyId?: string, groupId?: string) {
    // Only the common (company-scoped, no group filter) list is cached.
    if (groupId) return roleRepository.findAll(companyId, groupId);
    return cached(rolesKey(companyId), CACHE_TTL.static, () => roleRepository.findAll(companyId));
  }

  async findById(id: string) {
    const role = await roleRepository.findById(id);
    if (!role) throw new NotFoundError('Role not found');
    return role;
  }

  async create(dto: CreateRoleDTO) {
    const code = await generateSystemCode({
      prefix: 'ROLE',
      label: dto.name,
      exists: async (candidate) => Boolean(await roleRepository.findByCode(candidate)),
    });

    const existing = await roleRepository.findByCode(code);
    if (existing) throw new ConflictError(`Role code "${code}" already exists`);

    this.validateScope(dto);

    const role = await roleRepository.create({
      ...dto,
      code,
    });

    await invalidateRoles(dto.companyId);

    await eventBus.publish({
      name: DomainEvents.ROLE_CREATED,
      aggregateId: role.id,
      aggregateType: 'Role',
      data: dto,
      metadata: { eventId: uuidv4(), occurredAt: new Date() },
    });

    return role;
  }

  async update(id: string, dto: UpdateRoleDTO) {
    const role = await this.findById(id);

    if (role.isSystem) {
      throw new ValidationError('System roles cannot be modified');
    }

    this.validateImmutableScope(role, dto);

    if (dto.code && dto.code !== role.code) {
      throw new ValidationError('Role code is generated by system and cannot be changed');
    }

    if (dto.code === role.code) {
      delete dto.code;
    }

    if (dto.name && dto.name.trim() === role.name) {
      delete dto.name;
    }

    if (dto.description !== undefined && dto.description === role.description) {
      delete dto.description;
    }

    if (dto.priority !== undefined && dto.priority === role.priority) {
      delete dto.priority;
    }

    this.validateScope(dto);

    const updated = await roleRepository.update(id, dto);

    await invalidateRoles(role.companyId);

    await eventBus.publish({
      name: DomainEvents.ROLE_UPDATED,
      aggregateId: id,
      aggregateType: 'Role',
      data: dto,
      metadata: { eventId: uuidv4(), occurredAt: new Date() },
    });

    return updated;
  }

  async delete(id: string) {
    const role = await this.findById(id);
    if (role.isSystem) {
      throw new ValidationError('System roles cannot be deleted');
    }
    await roleRepository.softDelete(id);

    await invalidateRoles(role.companyId);

    await eventBus.publish({
      name: DomainEvents.ROLE_DELETED,
      aggregateId: id,
      aggregateType: 'Role',
      data: {},
      metadata: { eventId: uuidv4(), occurredAt: new Date() },
    });
  }

  async getPermissions(roleId: string) {
    await this.findById(roleId);
    return permissionRepository.getRolePermissions(roleId);
  }

  async assignPermissions(roleId: string, dto: AssignPermissionsDTO) {
    const role = await this.findById(roleId);

    if (role.isSystem) {
      throw new ValidationError('System role permissions cannot be modified');
    }

    // Verify all permissions exist
    const permissions = await permissionRepository.findByIds(dto.permissionIds);
    if (permissions.length !== dto.permissionIds.length) {
      throw new NotFoundError('One or more permissions not found');
    }

    await permissionRepository.assignToRole(roleId, dto.permissionIds);

    await eventBus.publish({
      name: DomainEvents.PERMISSION_ASSIGNED,
      aggregateId: roleId,
      aggregateType: 'Role',
      data: { permissionIds: dto.permissionIds },
      metadata: { eventId: uuidv4(), occurredAt: new Date() },
    });

    logger.info(`Permissions assigned to role ${role.name}: ${dto.permissionIds.length} permissions`);
    return permissionRepository.getRolePermissions(roleId);
  }

  async assignToUser(userId: string, dto: AssignUserRolesDTO) {
    // Verify roles exist
    for (const roleId of dto.roleIds) {
      const role = await roleRepository.findById(roleId);
      if (!role) throw new NotFoundError(`Role ${roleId} not found`);
    }

    // Remove existing roles
    await prisma.userRole.deleteMany({ where: { userId } });

    // Assign new roles
    const userRoles = await prisma.userRole.createMany({
      data: dto.roleIds.map((roleId) => ({
        userId,
        roleId,
        companyId: dto.companyId,
        groupId: dto.groupId,
        scopeType: dto.scopeType as any,
      })),
    });

    await eventBus.publish({
      name: DomainEvents.ROLE_ASSIGNED,
      aggregateId: userId,
      aggregateType: 'User',
      data: { roleIds: dto.roleIds },
      metadata: { eventId: uuidv4(), occurredAt: new Date() },
    });

    return userRoles;
  }

  async getUserRoles(userId: string) {
    return prisma.userRole.findMany({
      where: { userId },
      include: {
        role: {
          include: {
            _count: { select: { rolePermissions: true } },
          },
        },
      },
    });
  }

  private validateScope(dto: Partial<CreateRoleDTO>): void {
    if (dto.scope === 'GLOBAL' && dto.companyId) {
      throw new ValidationError('Global roles cannot be scoped to a company');
    }
    if (dto.scope === 'COMPANY' && !dto.companyId) {
      throw new ValidationError('Company-scoped roles must have a companyId');
    }
    if (dto.scope === 'GROUP' && !dto.groupId) {
      throw new ValidationError('Group-scoped roles must have a groupId');
    }
  }

  private validateImmutableScope(
    role: { scope: string; companyId?: string | null; groupId?: string | null },
    dto: UpdateRoleDTO
  ): void {
    if (dto.scope && dto.scope !== role.scope) {
      throw new ValidationError('Role scope cannot be changed after creation');
    }

    if (dto.companyId !== undefined && dto.companyId !== (role.companyId ?? undefined)) {
      throw new ValidationError('Role company binding cannot be changed after creation');
    }

    if (dto.groupId !== undefined && dto.groupId !== (role.groupId ?? undefined)) {
      throw new ValidationError('Role group binding cannot be changed after creation');
    }
  }
}

export const roleService = new RoleService();

export class PermissionService {
  // Permissions are seeded and immutable at runtime — TTL-only cache, no invalidation.
  async findAll(module?: string) {
    return cached(cacheKey(module ?? 'all', 'permissions'), CACHE_TTL.static, () =>
      permissionRepository.findAll(module)
    );
  }

  async getUserPermissions(userId: string) {
    return permissionRepository.getUserPermissions(userId);
  }
}

export const permissionService = new PermissionService();
